---
title: "<br> STAD SAM Oxytocin" 
subtitle: "Initial Analysis"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
            # toc: true
            # toc_depth: 2
            # number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include=FALSE}
# General R options
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation
options(repos = c(getOption("repos")["CRAN"], CRANextra = "https://mirror.clientvps.com/CRAN/"))  # use CRAN as default, set CRANextra to Nürnberg mirror


if (!require("pacman")) install.packages("pacman", dependencies = TRUE)
packages <- c(
  "papaja",
  "here", "fs",
  "conflicted",
  "rio",
  "tidyverse", 
  "psych",          
  "rstatix", "ggstatsplot",
  "ggplot2", "ggpubr", "scales",
  "report"
  # , ...
)
pacman::p_load(char = packages)

# Set here to Rnotebook directory
here::set_here()
unloadNamespace("here")                   # need new R session or unload namespace for .here file to take precedence over .Rproj
notebook_name <- fs::path_file(here::here())

# Solve conflicts in favor of tidyverse
conflicted::conflict_prefer("filter", winner = "dplyr")
conflicted::conflict_prefer("select", winner = "dplyr")
conflicted::conflict_prefer("slice", winner = "dplyr")
conflicted::conflict_prefer("rename", winner = "dplyr")
conflicted::conflict_prefer("count", winner = "dplyr")

# Set kintr options including root.dir pointing to the .here file in Rnotebook directory
knitr::opts_chunk$set(
  root.dir = here::here(),
  #fig.width = 5, fig.asp = 1/3, 
  comment = "#",
  collapse = TRUE,
  echo = TRUE, warning = TRUE, message = TRUE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# Themes for ggplot2 plotting (here used APA style)
theme_set(papaja::theme_apa())
```



<!-- Functions -->

# Define functions

```{r}
```


<!-- Report -->

# Read data

```{r}
df_sam_ox <- rio::import("rezultate_oxy+protT_sam_sem nov 2022.xlsx", which = "SAM")
df_sam_ox <- df_sam_ox[, 2:5]
df_sam_ox <- 
  df_sam_ox %>% 
  janitor::clean_names() %>% 
  tidyr::separate_wider_delim(id_proba, delim = "/", names = c("id", "study", "prepost")) %>% 
  mutate(id = as.numeric(id))

df_arsq <- rio::import(file = "DATE SAM,2022_2022-11-27.xlsx", which = "ARSQ", skip = 1)
df_info <- df_arsq[, 1:5]
rm(df_arsq)

# Join dataframes to add condition 
df_sam_ox <- left_join(df_sam_ox, df_info, by = c("id" = "ID"))
```

# Stats

## SAM

```{r, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}
df_sam_ox %>%
  mutate(prepost = factor(prepost, levels = c("PRE", "POST"))) %>% 
  group_by(id, Conditia) %>% 
  filter(n() > 1) %>%                      # exclude incomplete
  ungroup() %>% 
  ggstatsplot::grouped_ggwithinstats(
    x = prepost,
    y = oxitocina_normalizata,
    grouping.var = Conditia, 
    type = "p",
    bf.message = FALSE,
    annotation.args = list(title = "Pre & Post OX data", subtitle = "")
  )

df_sam_ox %>%
  mutate(prepost = factor(prepost, levels = c("PRE", "POST"))) %>% 
  filter(oxitocina_normalizata < 3) %>%    # exclude outlier from "VR miros"
  group_by(id, Conditia) %>% 
  filter(n() > 1) %>%                      # exclude incomplete
  ungroup() %>% 
  ggstatsplot::grouped_ggwithinstats(
    x = prepost,
    y = oxitocina_normalizata,
    grouping.var = Conditia,
    type = "p",
    bf.message = FALSE,
    annotation.args = list(title = "Pre & Post OX data", subtitle = "Outlier excluded from VR miros")
  )
```


<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
