---
title: "<br> PA4 - covid" 
subtitle: "Report"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
            # toc: true
            #  toc_depth: 2
            #  number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include=FALSE}
# kintr options
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  error = TRUE,
  echo = TRUE, warning = FALSE, message = FALSE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# General R options and info
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation

# Load packages
if (!require("pacman")) install.packages("pacman")
packages <- c(
  "papaja",
  "tidyverse",       
  "psych", "PerformanceAnalytics",          
  "broom", "rstatix",
  "summarytools", "tadaatoolbox",           
  "ggplot2", "ggpubr", "scales",        
  "rio",
  "ggpubr", "rstatix", "broom", "emmeans", "rlang",
  "pwr"
  # , ...
)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages)

# Themes for ggplot2 ploting (here used APA style)
theme_set(theme_apa())
```





<!-- Report -->


# Define Functions

```{r def_fun}
library(purrr)
library(tidyr)
library(ggplot2)
library(scales)
library(stringr)

func_percent <- function(df){
    df %>%                            # needs [, drop = FALSE] or tibble because coertion to vetor will crash it
      #purrr::keep(is.factor) %>% 
      tidyr::pivot_longer(cols = dplyr::everything()) %>%
      dplyr::count(name, value) %>%    
      group_by(name) %>%          # now required with changes to dplyr::count()
      mutate(pct = prop.table(n))
}


func_barplot_factor <- function(df){
    df %>%                            # needs [, drop = FALSE] or tibble because coertion to vetor will crash it
    #purrr::keep(is.factor) %>% 
    tidyr::pivot_longer(cols = dplyr::everything(), names_to = "name",   values_to = "value") %>%
    dplyr::mutate_at(vars("name"), stringr::str_wrap, 30) %>%                             # just to wrap long text of col names to title
    group_by(name) %>%          # now required with changes to dplyr::count()
    dplyr::count(name, value) %>%                   
    mutate(pct = prop.table(n)) %>%  
    ggplot2::ggplot(aes(x = value, y = pct, label = scales::percent(pct, accuracy = 2))) +
    ggplot2::geom_bar(stat = "identity") + 
    ggplot2::facet_wrap(~ name, scales = "free") +
    geom_text(position = position_dodge(width = .9),    # move to center of bars
              vjust = -0.5,                             # nudge above top of bar
              size = 3) +
    ggtitle("") +
    ylab("Percentage %") + xlab("") + 
    scale_fill_grey(start = 0.8, end = 0.2, na.value = "red", aesthetics = "fill")
}  

```


# Read, Clean, Recode

```{r red_clean_recode_merge, results='hide', message=FALSE}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Read, Clean, Recode, Unite
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

## Read files
folder <- "C:/Users/Mihai/Desktop/R Notebooks/notebooks/PA4-report"
file <- "Date_pt_analiza_PA4online.xlsx"

setwd(folder)

# ID df
id_df <- rio::import(file.path(folder, file),
                               skip = 1, which = "ID-uri atribuite")   
id_df <- 
  id_df %>%
  dplyr::mutate(ID = stringr::str_replace_all(ID, fixed(" "), ""))     # remove white spaces
all(id_df$ID == toupper(id_df$ID))                                     # check if all are upper case

firstform_df <- rio::import(file.path(folder, file),
                               skip = 0, which = "Formular de înscriere și consim") 
colnames(firstform_df)[7] <- "e-mail"

baseline_df <- dplyr::left_join(id_df, firstform_df, by = "e-mail")
baseline_df <- baseline_df[, c(4:9, 2, 10:ncol(baseline_df), 1,3)]       # move cols from id_df to back so we have matching cols index for baseline_df & firstform_df
all.equal(colnames(baseline_df)[1:72], colnames(firstform_df)[1:72])             # check if colnames match, except ID and name that where added

table(baseline_df$ID) # ID 9C is doubled, completed 2 times
which(baseline_df$ID == "9C")  # ID 9C row 27 is partially completed, excuted it
baseline_df <- baseline_df[-27 ,]
```


```{r tables}
# 10:13
# 14:15
# 17:22  # motive de stat in casa
# 23     # stres covid
# 24:30  # aspecte strensnte
# 31:39  # confort covid


firstform_df[, 10:13] %>%
  func_percent() %>%
  knitr::kable(digits = 2) %>%
  kableExtra::column_spec(1:2, width = "10cm")

firstform_df[, 14:15] %>%
  func_percent() %>%
  knitr::kable(digits = 2) %>%
  kableExtra::column_spec(1:2, width = "10cm")

firstform_df[, 23, drop = FALSE] %>%
  func_percent() %>%
  knitr::kable(digits = 2) %>%
  kableExtra::column_spec(1:2, width = "10cm")   

firstform_df[, 17:22] %>%
  func_percent() %>%
  knitr::kable(digits = 2) %>%
  kableExtra::column_spec(1:2, width = "10cm")

firstform_df[, 24:29] %>%
  func_percent() %>%
  knitr::kable(digits = 2) %>%
  kableExtra::column_spec(1:2, width = "10cm")


firstform_df[, 30, drop = FALSE] %>%
  func_percent() %>%
  knitr::kable(digits = 2) %>%
  kableExtra::column_spec(1:2, width = "10cm")
  


firstform_df[, 31:38] %>%
  func_percent() %>%
  knitr::kable(digits = 2) %>%
  kableExtra::column_spec(1:2, width = "10cm")

firstform_df[, 39, drop = FALSE] %>%
  func_percent() %>%
  knitr::kable(digits = 2) %>%
  kableExtra::column_spec(1:2, width = "10cm")

```


```{r plots, fig.height=18, fig.width=14}
firstform_df[, 17:22] %>%
  func_barplot_factor()

firstform_df[, 24:29] %>%
  func_barplot_factor()


firstform_df[, 31:38] %>%
 func_barplot_factor()


```





<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
