---
title: "<br> O1A Report" 
subtitle: "Final Report"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    pdf_document: 
            toc: true
            toc_depth: 2
            number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include = FALSE}
# kintr options
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  echo = TRUE, warning = TRUE, message = TRUE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# General R options and info
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation

# Load packages
if (!require("pacman")) install.packages("pacman")
packages <- c(
  "tidyverse",      # best thing that happend to me
  "psych",          # general purpose toolbox for personality, psychometric theory and experimental psychology
  "papaja",         # for APA style
  "broom",          # for tidy modelling
  "ggplot2",        # best plots
  "ggpubr",         # ggplot2 to publication quality
  "DT",             # nice searchable and downloadable tables
  "summarytools"
  # , ...
)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages)

# Themes for ggplot2 ploting (here used APA style)
theme_set(theme_apa())
```

```{r working_directory, include = FALSE}
# if needed
# wd = "./o1a-report"
# setwd(wd)
```


<!-- Report -->


# Load data

```{r raw_data, results = 'hide', cache.extra = file.info("diamonds.csv")}
# Read
file = "DATE O1A Complete.xlsx"

Date <- readxl::read_xlsx(file, sheet = "Date zilnice", skip = 5, col_names = FALSE)
```


## Processing data

```{r processed_data, cache = TRUE, dependson = "raw_data"}
# Clean
varnames <- c("Nr_crt", "ID", "Nume_Prenume", "Zi", "Vas_stres_pre", "Vas_bine_pre",
             sprintf("Stais_pre_%01d", seq(1,20)),
             "SOP",
             "IOS_mama", "IOS_tata", "IOS_iubit", "IOS_prieten", "IOS_personalitate",
             "Vas_rel_global", "Vas_rel_arousal",
             "CRQ_1", "CRQ_2", "CRQ_3", "CRQ_4", "CRQ_5", "CRQ_6",
             "Vas_stres_post", "Vas_bine_post",
             sprintf("Stais_post_%01d", seq(1,20))
)
names(Date) <- varnames   # nume noi
Date <- Date[-c(1:2),]    # scoatem randurile cu numele precedente
Date$Nr_crt <- 1:nrow(Date)   # era gol, asa ca numerotam randurile ca sa avem acesta variabila 

# Process NAs
Date <- Date %>% 
    na_if("na") %>%  
    mutate(NA_per_row = rowSums(is.na(.)))     # count NAs by row

Date <- Date %>% 
    filter(NA_per_row < 20)         # arbitrary cutoff for NAs on columns ... it is normal to have 4 NAs for all columns

# Convert to numeric
varsnumeric <- c("Zi", "Vas_stres_pre", "Vas_bine_pre",
                 sprintf("Stais_pre_%01d", seq(1,20)),
                 "IOS_mama", "IOS_tata", "IOS_iubit", "IOS_prieten", "IOS_personalitate",
                 "Vas_rel_global", "Vas_rel_arousal",
                 "CRQ_1", "CRQ_2", "CRQ_3", "CRQ_4", "CRQ_5", "CRQ_6",
                 "Vas_stres_post", "Vas_bine_post",
                  sprintf("Stais_post_%01d", seq(1,20)))

Date <- Date %>% 
  mutate_at(varsnumeric, as.numeric)

# which(Date$Stais_post_11 == 47)    # typo Stais_post_11 value of 47 -> corrected to 4
Date$Stais_post_11[Date$Stais_post_11 == 47] <- 4
```

<!-- Inspect Data - switched off -->
```{r inspectdata, echo=FALSE, results="hide"} 
# print(summarytools::dfSummary(Date, style = 'grid', plain.ascii = FALSE, graph.magnif = 0.85),    # suppress output
#       method = 'render', headings = FALSE)
# str(Date, list.len=ncol(Date))  # data types are fine
```


## Compute new variables

```{r derived_data, cache = TRUE, dependson = "processed_data"}
# Compute new variables 
Conditie <- Date %>% 
    select(Nr_crt, ID, IOS_mama, IOS_tata, IOS_iubit, IOS_prieten, IOS_personalitate) %>% 
    gather(type, value, -c(Nr_crt, ID)) %>% 
    mutate(Conditie = ifelse(!is.na(value), type, NA) ) %>%
    mutate(Conditie = str_replace(Conditie, "IOS_", "")) %>%
    arrange(Nr_crt) %>%
    select(Conditie) %>% na.omit() 
Date$Conditie <- Conditie$Conditie     # tidyverse returns tibble, must do this
IOS <- Date %>% 
  mutate(IOS = coalesce(IOS_mama, IOS_tata, IOS_iubit, IOS_prieten, IOS_personalitate)) %>%
  select(IOS)
Date$IOS <- IOS$IOS   # tidyverse returns tibble, must do this
rm(Conditie, IOS)    # remove 2 tibbles

# Scoring Stai   (convert numeric - VAS)
itemiVAS <- c(5, 6, 41, 42)

itemiStaiS_pre <- 7:26
itemiStaiS_post <- 43:62
ReversedItems <- c(1,2,5,8,10,11,15,16,19,20)

Date <- Date %>%                 
  replace(Date == "na", NA) %>%        # scimbam codarea cu na a Doinei
  mutate_at(vars(itemiStaiS_pre), funs(as.numeric)) %>%        # facem coloanele numerice pt STAI
  mutate_at(vars(itemiStaiS_post), funs(as.numeric)) %>% 
  mutate_at(vars(itemiVAS), funs(as.numeric))

Date[ ,itemiStaiS_pre[ReversedItems]] = 5 - Date[ ,itemiStaiS_pre[ReversedItems]]
Date[ ,itemiStaiS_post[ReversedItems]] = 5 - Date[ ,itemiStaiS_post[ReversedItems]]

Date$StaiS_pre = rowSums(Date[ ,itemiStaiS_pre], na.rm=T ) * NA ^ (rowSums(!is.na(Date[ ,itemiStaiS_pre])) == 0)
Date$StaiS_post = rowSums(Date[ ,itemiStaiS_post], na.rm=T ) * NA ^ (rowSums(!is.na(Date[ ,itemiStaiS_post])) == 0)
```


## Table of derived variables

```{r table_derived_data}
varnottable <- c("Nume_Prenume", "NA_per_row", 
                 sprintf("Stais_pre_%01d", seq(1,20)), 
                 sprintf("Stais_post_%01d", seq(1,20)))

Date %>%                              
  select(-varnottable) %>%
    DT::datatable(                                  # excel downloadable  DT table
      extensions = 'Buttons',
      options = list(pageLength = 20,
                     scrollX='500px', 
                     dom = 'Bfrtip', 
                     buttons = c('excel', "csv")))
```


<br>

# STAI-Y

## Plots with p values
```{r stai_plot, fig.width = 10, fig.asp = 0.8}
## STAI plot 
Staimelt <- Date[, c("ID", "Conditie", "StaiS_pre","StaiS_post")] %>% 
  gather("StaiS_pre", "StaiS_post", key = "Stai_cond", value = "value") %>% 
  mutate_at(vars(c(1, 2, 3)), funs(as.factor)) %>% 
  mutate(Stai_cond = factor(Stai_cond, levels = c("StaiS_pre","StaiS_post"))) # %>%    # change factor order for plot pre, post

ggplot(Staimelt, aes(x = Stai_cond, y = value)) +
  geom_boxplot() +
  facet_wrap(~Conditie) +
  ggpubr::stat_compare_means(method = "t.test", paired = TRUE, comparisons = list(c("StaiS_pre","StaiS_post")))
```

## t tests
```{r stai_ttest}
## STAI tables
Date %>% 
  group_by(Conditie) %>% 
  do(broom::tidy(t.test(.$StaiS_pre, 
                        .$StaiS_post, 
                        mu = 0, 
                        alt = "two.sided", 
                        paired = TRUE, 
                        conf.level = 0.95))) %>%
  knitr::kable(digits = 2)
```


<br>

# VAS Stres

## Plots with p values
```{r vasS_plot, fig.width = 10, fig.asp = 0.8}
## Vas Stres plot 
Vasstresmelt <- Date[, c("ID", "Conditie", "Vas_stres_pre","Vas_stres_post")] %>% 
  gather("Vas_stres_pre","Vas_stres_post", key = "Vas_stres_cond", value = "value") %>% 
  mutate_at(vars(c(1,2,3)), funs(as.factor)) %>% 
  mutate_at(vars(c(4)), funs(as.numeric)) %>% 
  mutate(Vas_stres_cond = factor(Vas_stres_cond, levels = c("Vas_stres_pre","Vas_stres_post"))) # change factor order for plot pre, post

ggplot(Vasstresmelt, aes(x = Vas_stres_cond, y = value)) +
  geom_boxplot() +
  facet_wrap(~Conditie) +
  ggpubr::stat_compare_means(method = "t.test", paired = TRUE, comparisons = list(c("Vas_stres_pre","Vas_stres_post")))
```

## t tests
```{r vasS_ttest}
## Vas Stres tables
Date %>% 
  group_by(Conditie) %>% 
  do(broom::tidy(t.test(.$Vas_stres_pre, 
                        .$Vas_stres_post, 
                        mu = 0, 
                        alt = "two.sided", 
                        paired = TRUE, 
                        conf.level = 0.95))) %>%
  knitr::kable(digits = 2)
```


<br>

# VAS Wellbeing

## Plots with p values
```{r vasB_plot, fig.width = 10, fig.asp = 0.8}
## Vas Stres plot 
Vasbinemelt <- Date[, c("ID", "Conditie", "Vas_bine_pre","Vas_bine_post")] %>% 
  gather("Vas_bine_pre","Vas_bine_post", key = "Vas_stres_cond", value = "value") %>% 
  mutate_at(vars(c(1,2,3)), funs(as.factor)) %>% 
  mutate_at(vars(c(4)), funs(as.numeric)) %>% 
  mutate(Vas_stres_cond = factor(Vas_stres_cond, levels = c("Vas_bine_pre","Vas_bine_post"))) # change factor order for plot pre, post

ggplot(Vasbinemelt, aes(x = Vas_stres_cond, y = value)) +
  geom_boxplot() +
  facet_wrap(~Conditie) +
  ggpubr::stat_compare_means(method = "t.test", paired = TRUE, comparisons = list(c("Vas_bine_pre","Vas_bine_post")))
```

## t tests
```{r vasB_ttest}
## Vas Stres tables
Date %>% 
  group_by(Conditie) %>% 
  do(broom::tidy(t.test(.$Vas_bine_pre, 
                        .$Vas_bine_post, 
                        mu = 0, 
                        alt = "two.sided", 
                        paired = TRUE, 
                        conf.level = 0.95))) %>%
  knitr::kable(digits = 2)
```


# Melt dataframe for future analyses

```{r wideformat_data}
# Data from Long to Wide
meltDate <- 
  Date %>% 
    select(ID, Conditie, 
           Vas_stres_pre, Vas_stres_post,
           Vas_bine_pre, Vas_bine_post,
           StaiS_pre, StaiS_post) %>%
      gather(variable, value, Vas_stres_pre:StaiS_post) %>%
      unite(VarCond, variable, Conditie) %>% 
      spread(VarCond, value)

# Some rownames are typos (ID 1 and 26)
func_collapseduplicate <- function(x) {           # collapses duplicate rows, but if all are NA returns NA
  sum(x, na.rm=T ) * NA ^ (sum(!is.na(x)) == 0)
}

meltDate <-
  meltDate %>%
    mutate(ID = word(ID, 1)) %>%
    group_by(ID) %>% 
    summarise_all(func_collapseduplicate)

  
# Test if all results are the same -- all seems good
# t.test(meltDate$Vas_bine_pre_prieten, meltDate$Vas_bine_post_prieten, 
#                         mu = 0, 
#                         alt = "two.sided", 
#                         paired = TRUE, 
#                         conf.level = 0.95)

meltDate %>%
      DT::datatable(                                  # excel downloadable  DT table
      extensions = 'Buttons',
      options = list(pageLength = 20,
                     scrollX='500px', 
                     dom = 'Bfrtip', 
                     buttons = c('excel', "csv")))
```



<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
