---
title: "<br> Rezidential" 
subtitle: "Inferential Statistics"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
    #         toc: true
    #         toc_depth: 2
    #         number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include = FALSE}
# kintr options
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  echo = TRUE, 
  cache = TRUE, 
  warning = FALSE, message = FALSE   # WHEN NOTEBOOK IS FINISHED ... until then leave: warning = TRUE, message = TRUE        
)

# General R options and info
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation

# Load packages
if (!require("pacman")) install.packages("pacman")
packages <- c(
  "knitr", "kableExtra", "papaja",  
  "tidyverse", "plyr",      
  "psych", "psycho",           
  "broom", "summarytools", "tadaatoolbox", "PerformanceAnalytics",          
  "ggplot2", "ggpubr", "scales",        
  "rio",
  "Hmisc", 
  "GGally", "corrplot", "RColorBrewer", 
  "car",
  "medmod", 
  "lavaan", "semTools", "semPlot"
  # , ...
)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages)

# Themes for ggplot2 ploting (here used APA style)
theme_set(theme_apa())
```

```{r working_directory, include = FALSE}
# if needed
# wd = "./Rezidential"
# setwd(wd)
```


<!-- REPORT -->


# Load data

```{r rds_data, results = 'hide', cache.extra = file.info("Data_Rezidential.RDS")}
## Read
filename <- "Data_Rezidential.RDS"   

Data <- readRDS(filename)  
```


## Modify ACE Score to take into account that all are institutionalized

```{r derived_data, cache = TRUE, dependson = "rds_data"}
Data$CYW <- ifelse(Data$CYW == 0, 0, Data$CYW - 1) 
```


# Typo in ASCQ
```{r typos}
Data$AAvoid[which(Data$asc_12 == 11)] <- Data$AAvoid[which(Data$asc_12 == 11)] - 10
Data$asc_12[which(Data$asc_12 == 11)] <- 1   # "ASCQ_f" "ASCQ_d" remain uncorrected

```

# Typo in Age
```{r typo_adol_age}
Data[Data$ID == 505, ]$varsta <- 15   # age 15 instead of 5
```


## Minore transformations to Data

```{r transform_data, echo=FALSE}
Data <- 
  Data %>%
  dplyr::mutate(ASCQ_d = as.factor(ifelse(ASCQ_d == 0, "Secur", "Unsecur"))) %>%
  dplyr::mutate(gen = forcats::fct_recode(gen, Fete = "f", Baieti = "m")) %>%
  dplyr::mutate(tip_chestionar2 = forcats::fct_collapse(tip_chestionar, "5-8ani" = c("5-8ani", "5-8intarziere"))) %>%
  dplyr::mutate(CESD_d = factor(CESD_d, levels = c("0", "1"))) %>%
  dplyr::mutate(SCARED_d = factor(ifelse(Data$SCARED >= 25, 1, 0), levels = c("0", "1"))) %>%  # this was calculated wrongly
  dplyr::mutate(PD_d = factor(PD_d, levels = c("0", "1")),
                GAD_d = factor(GAD_d, levels = c("0", "1")),
                SepA_d= factor(SepA_d, levels = c("0", "1")),
                SAD_d = factor(SAD_d, levels = c("0", "1")),
                SchA_d = factor(SchA_d, levels = c("0", "1")))
    
Data_child <-
  Data %>%
  filter(tip_chestionar %in% c("5-8ani", "5-8intarziere"))
  
Data_adol <-
  Data %>%
  filter(tip_chestionar == "9-18ani") %>%
  dplyr::mutate(intarziere = tidyr::replace_na(intarziere, 0))
```



# Desc CESD

```{r}
library(patchwork)

Data %>%
  dplyr::group_by(CESD) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(freq = n / sum(n)) %>%
  print(n = Inf)

p_cesd_1 <-
  Data %>%
    ggplot(aes(x = CESD, fill = CESD_d)) +
      geom_histogram(bins = 55, color = "black") +  
      geom_vline(xintercept = 15, linetype = "dashed", color = "black", size = 1.2) +
      scale_y_continuous(
        sec.axis = sec_axis(trans = ~./nrow(Data), labels = percent, 
                            name = "Proportie (%)")) +
      scale_fill_manual(breaks = c("0", "1"), 
                         values = wesanderson::wes_palette("Royal1")[1:2]) +
      ylab("Frecventa") +
      scale_x_continuous(breaks = seq(0, 55, by = 5)) +
      guides(fill = FALSE) +
      facet_wrap(~tip_chestionar2) +
      ggtitle("Niveluri de depresie")

p_cesd_2 <-
  Data_child %>%
    dplyr::mutate(CESD_d = forcats::fct_rev(CESD_d)) %>%
    ggstatsplot::ggpiestats(
      x = CESD_d,
      y = gen,
      type = "parametric", 
      bf.message = FALSE,
      package = "wesanderson",
      palette = "Royal1",
      title = "Copii (5-8 ani)")

p_cesd_3 <-
  Data_adol %>%
    dplyr::mutate(CESD_d = forcats::fct_rev(CESD_d)) %>%
    ggstatsplot::ggpiestats(
      x = CESD_d,
      y = gen,
      type = "parametric", 
      bf.message = FALSE,
      package = "wesanderson",
      palette = "Royal1",
      title = "Preadolescenti si adolescenti (9-18 ani)")



p_cesd_1 / (p_cesd_2 | p_cesd_3)  

# ggsave(plot = p_cesd_1, filename = "p_cesd_1.png", width = 10, height = 8, units = "in", dpi = 500)
# ggsave(plot = p_cesd_2, filename = "p_cesd_2.png", width = 7, height = 7, units = "in", dpi = 500)
# ggsave(plot = p_cesd_3, filename = "p_cesd_3.png", width = 7, height = 7, units = "in", dpi = 500)
```


# Desc SCARED

```{r}
library(patchwork)

Data %>%
  dplyr::group_by(SCARED) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(freq = n / sum(n)) %>%
  print(n = Inf)

p_scared_1 <-
  Data %>%
  ggplot(aes(x = SCARED, fill = SCARED_d)) +
  geom_histogram(bins = 85, color = "black") +  
  geom_vline(xintercept = 25, linetype = "dashed", color = "black", size = 1.2) +
  scale_y_continuous(
    sec.axis = sec_axis(trans = ~./nrow(Data), labels = percent, 
                        name = "Proportie (%)")) +
  scale_fill_manual(breaks = c("0", "1"), 
                    values = wesanderson::wes_palette("Royal1")[1:2]) +
  ylab("Frecventa") +
  scale_x_continuous(breaks = seq(0, 85, by = 5)) +
  guides(fill = FALSE) +
  facet_wrap(~tip_chestionar2) +
  ggtitle("Niveluri de anxietate")

p_scared_2 <-
  Data_child %>%
  dplyr::mutate(SCARED_d = forcats::fct_rev(SCARED_d)) %>%
  ggstatsplot::ggpiestats(
    x = SCARED_d,
    y = gen,
    type = "parametric", 
    bf.message = FALSE,
    package = "wesanderson",
    palette = "Royal1",
    title = "Copii (5-8 ani)")

p_scared_3 <-
  Data_adol %>%
  dplyr::mutate(SCARED_d = forcats::fct_rev(SCARED_d)) %>%
  ggstatsplot::ggpiestats(
    x = SCARED_d,
    y = gen,
    type = "parametric", 
    bf.message = FALSE,
    package = "wesanderson",
    palette = "Royal1",
    title = "Preadolescenti si adolescenti (9-18 ani)")



p_scared_1 / (p_scared_2 | p_scared_3)  

# ggsave(plot = p_scared_1, filename = "p_scared_1.png", width = 10, height = 8, units = "in", dpi = 500)
# ggsave(plot = p_scared_2, filename = "p_scared_2.png", width = 7, height = 7, units = "in", dpi = 500)
# ggsave(plot = p_scared_3, filename = "p_scared_3.png", width = 7, height = 7, units = "in", dpi = 500)
```


# GCIC

```{r}
Data_gci <- Data[, c(sprintf("gci_%d", 1:14), "OpenC", "CloseC", "centru")]

labels_gci <- 
  c("Foarte neadevărat",
  "Neadevărat",
  "Un pic neadevărat / Un pic adevărat",
  "Adevărat",
  "Foarte adevărat")

itemtext_gci <-
  c("1. Oamenii de la centru se poartă frumos cu mine.",
  "2. Am încredere în oamenii din centru.",
  "3. Oamenii de la centru mă înţeleg.",
  "4. Atunci când mă plâng de ceva, oamenii din centru mă iau în serios.",
  "5. Oamenii de la centru sunt corecți.",
  "6. Simt că aici, la centru, lucrez la îndeplinirea scopurilor mele.",
  "7. În acest centru sunt întotdeauna destui oameni care să mă ajute.",
  "8. Oamenii din centru se țin de cuvânt.",
  "9. Pot să cer ajutor de la oamenii din centru atunci când am nevoie.",
  "10. În acest centru, copiii au încredere unii în alții. (R)",
  "11. Aici, poți să ai încredere în toată lumea. (R)",
  "12. Haosul și gălăgia din centru mă înnebunesc.",
  "13. Sunt prea mulți copii aici.",
  "14. Oamenii de la centru sunt adesea prea ocupați ca să mă ajute.")

Data_gci <-
  Data_gci %>%
  mutate_at(vars(sprintf("gci_%d", 1:14)), ~as.factor(as.character(.))) %>%
  rename_at(vars(sprintf("gci_%d", 1:14)), ~itemtext_gci) %>%
  rename_at(vars("OpenC", "CloseC"), ~c("Climat deschis", "Climat închis")) %>%
  dplyr::rename(Centru = centru)

# Plots  # library(likert)
Likertobj_gci <- likert::likert(Data_gci[, 1:14], nlevels = 5)   # here are percentages

p_gcic_1 <-
  plot(Likertobj_gci, type = "bar", 
       centered = TRUE, center = 3, include.center = TRUE,              # "3" is neutral
       wrap = 40, low.color = 'burlywood', high.color = 'maroon',
       group.order = names(Data_gci[, 1:14])) +
    ylab("Procent") + 
    guides(fill = guide_legend(nrow = 1, title = "Răspuns")) +
    geom_vline(xintercept = 5.51) +
    labs(title = "Climatul de grup din centrul rezidential",
         caption = "Raspunsurile la itemii 10 si 11 au fost cotate invers.")

 
Data_gci %>%
  select("Climat deschis", "Climat închis") %>%
  gather() %>%
  rename_at(vars("key", "value"), ~c("Var", "Scor")) %>%
    ggpubr::ggviolin("Var", "Scor", fill = "Var",
      palette = c("#00AFBB", "#FC4E07"),
      add = "boxplot", add.params = list(fill = "white"),
      xlab = "", legend = "none") +
  stat_summary(fun.data = mean_se,  colour = "darkred")

ggsave(plot = p_gcic_1, filename = "p_gcic_1.png", width = 10, height = 10, units = "in", dpi = 500)
```


```{r}
Data_adol %>%
  dplyr::select("OpenC", "CloseC", "CESD", "SCARED", "R_Ind_a", "R_Care_a", "R_Cont_a", "CYRM_a") %>%
  PerformanceAnalytics::chart.Correlation()
```

# Mediation
## Adol

```{r}
Data_adol_standardized <- 
  Data_adol %>%
  dplyr::select("OpenC", "CloseC", "CESD", "SCARED", "CYRM_a", "PD", "GAD",  "SepA", "SAD") %>%
  mutate_all(~(scale(.) %>% as.vector))

# psych::mediate(CESD ~ OpenC + CloseC + (CYRM_a), data = Data_adol, zero = TRUE)
# psych::mediate(SCARED ~ OpenC + CloseC + (CYRM_a), data = Data_adol)

# psych::mediate(CESD + SCARED ~ OpenC + CloseC + (CYRM_a), data = Data_adol) # %>% summary()

# SCARED
# mod_adol <- psych::mediate(CESD + SCARED ~ OpenC + CloseC + (CYRM_a), data = Data_adol_standardized) 
# mod_adol %>% summary()
# mod_adol$boot$ci.ab

# GAD
summary(lm(CESD ~ OpenC + CloseC, data = Data_adol_standardized)); # ggstatsplot::ggcoefstats(lm(CESD ~ OpenC + CloseC, data = Data_adol_standardized))
summary(lm(GAD ~ OpenC + CloseC, data = Data_adol_standardized)); # ggstatsplot::ggcoefstats(lm(GAD ~ OpenC + CloseC, data = Data_adol_standardized))
# QuantPsyc::lm.beta(lm(GAD ~ OpenC + CloseC, data = Data_adol_standardized))

mod_adol <- psych::mediate(CESD + GAD ~ OpenC + CloseC + (CYRM_a), data = Data_adol_standardized) 
mod_adol %>% summary()
mod_adol$boot$ci.ab
```


## Child

```{r}
Data_child_standardized <- 
  Data_child %>%
  dplyr::select("OpenC", "CloseC", "CESD", "SCARED", "CYRM_k", "PD", "GAD",  "SepA", "SAD") %>%
  mutate_all(~(scale(.) %>% as.vector))

# SCARED
# mod_child <- psych::mediate(CESD + SCARED ~ OpenC + CloseC + (CYRM_k), data = Data_child_standardized)  
# mod_child %>% summary() 
# mod_child$boot$ci.ab

# GAD
# Data_child_standardized_gad <-
#   Data_child_standardized %>%
#   dplyr::select("OpenC", "CloseC", "CESD", "GAD", "CYRM_k") %>%
#   tidyr::drop_na()

summary(lm(CESD ~ OpenC + CloseC, data = Data_child_standardized)); # ggstatsplot::ggcoefstats(lm(CESD ~ OpenC + CloseC, data = Data_child_standardized))
summary(lm(GAD ~ OpenC + CloseC, data = Data_child_standardized)); # ggstatsplot::ggcoefstats(lm(GAD ~ OpenC + CloseC, data = Data_child_standardized))

mod_child <- psych::mediate(CESD + GAD ~ OpenC + CloseC + (CYRM_k), data = Data_child_standardized)  
mod_child %>% summary() 
mod_child$boot$ci.ab

```

<!--
## Adol & Child 

```{r}
Data_standardized <- 
  Data %>%
  dplyr::select("CYW", "OpenC", "CloseC", "CESD", "SCARED", "CYRM_a", "CYRM_k", "PD", "GAD",  "SepA", "SAD") %>%
  dplyr::mutate(CYRM = dplyr::coalesce(CYRM_a, CYRM_k)) %>%
  dplyr::select(-CYRM_a, -CYRM_k) %>% 
  mutate_all(~(scale(.) %>% as.vector))
Data_standardized <- cbind(Data_standardized, gen = Data$gen)


#psych::mediate(CESD + SCARED ~ CYW + CloseC + (CYRM), data = Data_standardized) 
mod_adolchild <- psych::mediate(CESD + SCARED ~ OpenC + CloseC + (CYRM), data = Data_standardized) 
mod_adolchild %>% summary()
mod_adolchild$boot$ci.ab

bla <- 
  Data_standardized %>%
  dplyr::select("OpenC", "CloseC", "CESD", CYRM, GAD) %>%
  drop_na()
```
-->


# lavvan Adol
<!--
```{r}
path_model <- '
OpenC ~~ CloseC
CESD ~~ SCARED
# CYRM_a ~ gen

# direct effect
 CESD ~ c1*OpenC
 CESD ~ c2*CloseC
 
 SCARED ~ c3*OpenC
 SCARED ~ c4*CloseC
 
# mediator
 CYRM_a ~ a1*OpenC
 CYRM_a ~ a2*CloseC
 
 CESD ~ b1*CYRM_a
 SCARED ~ b2*CYRM_a
 
# indirect effect (a*b)
 ab1 := a1*b1   # for c1: Open-CESD
 ab2 := a2*b1   # for c2: Close-CESD
 
 ab3 := a1*b2   # for c3: Open-SCARED
 ab4 := a2*b2   # for c4: Close-SCARED
 
# total effect
 total1 := c1 + (a1*b1)
 total2 := c2 + (a2*b1)
 
 total3 := c3 + (a1*b2)
 total4 := c4 + (a2*b2)
'

fit_path_model <- lavaan::sem(model = path_model, data = Data_adol, estimator = "ml", se = "bootstrap") # se = "bootstrap"
summary(fit_path_model, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)
semPaths(fit_path_model, what = "std", title = TRUE, curvePivot = TRUE, layout = "tree")

# significant standardized paths only
lavaanPlot::lavaanPlot(model = fit_path_model, 
                       graph_options = list(layout = "dot"), 
                       node_options = list(shape = "box", fontname = "Helvetica"), 
                       edge_options = list(color = "grey"), 
                       coefs = TRUE, stand = TRUE, covs = TRUE, 
                       sig = 0.05, stars = c("regress", "cov"))  # unstandardized: sig = 1.00
```


# lavvan Adol & Child

```{r}
path_model <- '
OpenC ~~ CloseC
CESD ~~ SCARED

# CYRM ~ CYW
# CESD ~ CYW
# SCARED ~ CYW

# direct effect
 CESD ~ c1*OpenC
 CESD ~ c2*CloseC
 
 SCARED ~ c3*OpenC
 SCARED ~ c4*CloseC
 
# mediator
 CYRM ~ a1*OpenC
 CYRM ~ a2*CloseC
 
 CESD ~ b1*CYRM
 SCARED ~ b2*CYRM
 
# indirect effect (a*b)
 ab1 := a1*b1   # for c1: Open-CESD
 ab2 := a2*b1   # for c2: Close-CESD
 
 ab3 := a1*b2   # for c3: Open-SCARED
 ab4 := a2*b2   # for c4: Close-SCARED
 
# total effect
 total1 := c1 + (a1*b1)
 total2 := c2 + (a2*b1)
 
 total3 := c3 + (a1*b2)
 total4 := c4 + (a2*b2)
'

fit_path_model <- lavaan::sem(model = path_model, data = Data_standardized, estimator = "ml", se = "bootstrap", test = "boot") # se = "bootstrap"
summary(fit_path_model, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)
parameterEstimates(fit_path_model, ci = TRUE, level = 0.95, boot.ci.type = "bca.simple", standardized = TRUE)
                   

# significant standardized paths only
lavaanPlot::lavaanPlot(model = fit_path_model, 
                       graph_options = list(layout = "dot"), 
                       node_options = list(shape = "box", fontname = "Helvetica"), 
                       edge_options = list(color = "grey"), 
                       coefs = TRUE, stand = TRUE, covs = TRUE, 
                       sig = 0.05, stars = c("regress", "cov"))  # unstandardized: sig = 1.00
```
-->



<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
