---
title: "<br> Balanced randomization for EEG O.4" 
subtitle: "Randomization O.4 - 20 subjects & 32 subjects"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
            # toc: true
            # toc_depth: 2
            # number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
---


```{r setup, include = FALSE}
# kintr options
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  echo = TRUE, warning = TRUE, message = TRUE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# General R options and info
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation

# Load packages
if (!require("pacman")) install.packages("pacman")
packages <- c(
  "tidyverse",      # best thing that happend to me
  "psych",          # general purpose toolbox for personality, psychometric theory and experimental psychology
  "papaja",         # for APA style
  "ggplot2",        # best plots
  "DT"              # data tables
  # , ...
)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages)

# Themes for ggplot2 ploting (here used APA style)
theme_set(theme_apa())
```


<br>

# Randomization Table for 20 Subjects

```{r randomize_blocks}
# Repetate
set.seed(101)
eeg_rand <- psych::block.random(20, c(Condition1 = 2, Order1 = 2)) 

table_eeg_rand <- 
  eeg_rand %>% 
  as.data.frame(.) %>%  
  mutate(Condition1 = case_when(Condition1 == 1 ~ "ogl" ,
                                Condition1 == 2 ~ "ctrl", 
                                TRUE ~ NA_character_)) %>%
  mutate(Order1 = case_when(Order1 == 1 ~ "Instr-Solo" ,
                            Order1 == 2 ~ "Solo-Instr", 
                            TRUE ~ NA_character_)) %>%
  mutate(Condition2 = if_else(Condition1 == "ogl", "ctrl", "ogl")) %>%
  mutate(Order2 = if_else(Order1 == "Instr-Solo", "Solo-Instr", "Instr-Solo")) %>%
  mutate(ID = 1:nrow(.)) %>%
  mutate(Set = rep(NA, nrow(.)),
         Instructor = rep(NA, nrow(.)))
  

table_eeg_rand %>%                              # excel downloadable  DT table
  select(blocks, ID, everything()) %>%
    DT::datatable(
      extensions = 'Buttons',
      options = list(pageLength = 40,
                     dom = 'Bfrtip', 
                     buttons = c('excel', "csv")))

# kable table
# table_eeg_rand %>%                             
#   select(blocks, ID, everything()) %>%
#   knitr::kable(caption = "Randomization Table", align = rep('c', 6))
```


<br>

## Check cross-tabs for each day

```{r randomize_check}

table_eeg_rand %>%
  select(Condition1, Order1) %>%
  ftable(row.vars = 1)
  # knitr::kable()

table_eeg_rand %>%
  select(Condition2, Order2) %>%
  ftable(row.vars = 1)

# all conditions are balanced by block
# table_eeg_rand %>%
#   filter(blocks == 1) %>%
#   select(Condition1, Instructor1, Order1) %>%
#   ftable(row.vars = 1)
```


<br>

##  Check balance 

```{r randimize_plot}
# pairs.panels(eeg_rand)

table_eeg_rand %>%
  select(-ID, -blocks, -Instructor, -Set) %>%
    pairs.panels()
```



<br>

# Randomization Table for 30 Subjects

```{r randomize_blocks30}
# Repetate
set.seed(101)
eeg_rand32 <- psych::block.random(32, c(Condition1 = 2, Order1 = 2, Set1 = 2)) 

table_eeg_rand32 <- 
  eeg_rand32 %>% 
  as.data.frame(.) %>%  
  mutate(Condition1 = case_when(Condition1 == 1 ~ "ogl" ,
                                Condition1 == 2 ~ "ctrl", 
                                TRUE ~ NA_character_)) %>%
  mutate(Order1 = case_when(Order1 == 1 ~ "Instr-Solo" ,
                            Order1 == 2 ~ "Solo-Instr", 
                            TRUE ~ NA_character_)) %>%
  mutate(Order1 = case_when(Set1 == 1 ~ "1-2" ,
                            Set1 == 2 ~ "2-1", 
                            TRUE ~ NA_character_)) %>%
  mutate(Condition2 = if_else(Condition1 == "ogl", "ctrl", "ogl")) %>%
  mutate(Order2 = if_else(Order1 == "Instr-Solo", "Solo-Instr", "Instr-Solo")) %>%
  mutate(Set2 = if_else(Set1 == "1-2", "2-1", "1-2")) %>%
  mutate(ID = 1:nrow(.)) %>%
  mutate(Instructor = rep(NA, nrow(.)))
  

table_eeg_rand32 %>%                              # excel downloadable  DT table
  select(blocks, ID, everything()) %>%
    DT::datatable(
      extensions = 'Buttons',
      options = list(pageLength = 40,
                     dom = 'Bfrtip', 
                     buttons = c('excel', "csv")))
```


<br>

## Check cross-tabs for each day

```{r randomize_check30}

table_eeg_rand32 %>%
  select(Condition1, Order1, Set1) %>%
  ftable(row.vars = 1)
  # knitr::kable()

table_eeg_rand32 %>%
  select(Condition2, Order2, Set1) %>%
  ftable(row.vars = 1)
```


<br>

##  Check balance 

```{r randimize_plot30}
# pairs.panels(eeg_rand)

table_eeg_rand32 %>%
  select(-ID, -blocks, -Instructor) %>%
    pairs.panels()
```




<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
