---
title: "<br> STAD SEM Oxytocin" 
subtitle: "Initial Analysis"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
            # toc: true
            # toc_depth: 2
            # number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include=FALSE}
# General R options
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation
options(repos = c(getOption("repos")["CRAN"], CRANextra = "https://mirror.clientvps.com/CRAN/"))  # use CRAN as default, set CRANextra to Nürnberg mirror


if (!require("pacman")) install.packages("pacman", dependencies = TRUE)
packages <- c(
  "papaja",
  "here", "fs",
  "conflicted",
  "rio",
  "tidyverse", 
  "psych",          
  "rstatix", "ggstatsplot",
  "ggplot2", "ggpubr", "scales",
  "report"
  # , ...
)
pacman::p_load(char = packages)

# Set here to Rnotebook directory
here::set_here()
unloadNamespace("here")                   # need new R session or unload namespace for .here file to take precedence over .Rproj
notebook_name <- fs::path_file(here::here())

# Solve conflicts in favor of tidyverse
conflicted::conflict_prefer("filter", winner = "dplyr")
conflicted::conflict_prefer("select", winner = "dplyr")
conflicted::conflict_prefer("slice", winner = "dplyr")
conflicted::conflict_prefer("rename", winner = "dplyr")
conflicted::conflict_prefer("count", winner = "dplyr")

# Set kintr options including root.dir pointing to the .here file in Rnotebook directory
knitr::opts_chunk$set(
  root.dir = here::here(),
  #fig.width = 5, fig.asp = 1/3, 
  comment = "#",
  collapse = TRUE,
  echo = TRUE, warning = TRUE, message = TRUE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# Themes for ggplot2 plotting (here used APA style)
theme_set(papaja::theme_apa())
```



<!-- Functions -->

# Define functions

```{r}
```


<!-- Report -->

# Read data

## Id data

```{r}
# IDs
ids_df <- read.csv(here::here("subjects.csv"))
ids_df <- ids_df[6:52, ]
nrow(ids_df) == length(unique(ids_df$id))
ids_df$id[duplicated(ids_df$id)]

ids_vec <- ids_df$id

# Fix "7sem" - "8sem" and "5sem" second
ids_df <- 
  ids_df %>% 
  group_by(id) %>%
  mutate(id = if_else(id == "7sem" & row_number() == 2, "8sem", id)) %>%
  distinct() %>%  # "25 sem c" apare dublat doar lasubjects.csv dar nu si in celelalte 2 .csv
  select(-c(nume, prenume, email))
```

## Match with external records for Cond

```{r}
# Merge Cond with ids_df
ids_elderly <- ids_df$id[1:14] # elderly - ids 1:14 (16 missing)
ids_rest <- ids_df$id[15:45]  # rest - ids (1:5,8:33) C  (missing: 6, 7)

elderly_cond <- c("NS", "pozitiv", "NS", "pozitiv", "neutru", "neutru", "NS", "pozitiv", "NS", "NS", "NS", "NS", "NS", "pozitiv")
length(unique(elderly_cond))
length(ids_df$id[1:14]) == length(elderly_cond)
rest_cond <- c("NS", "NS", "pozitiv", "pozitiv", "NS", "pozitiv", "NS", "pozitiv", "pozitiv", "pozitiv", "neutru", "neutru", 
               "pozitiv", "pozitiv", "pozitiv", "pozitiv", "neutru", "NS", "neutru", "NS", "neutru", "neutru", "neutru", 
               "neutru", "neutru", "NS", "NS", "NS", "neutru", "NS", "pozitiv")
length(unique(rest_cond))
length(ids_df$id[15:45]) == length(rest_cond)

ids_df$Cond <- c(elderly_cond, rest_cond)

# Make a simple id col for joining
ids_df$simple_id <- as.numeric(readr::parse_number(ids_df$id))  # id 22 = NA
```

## Ox data

```{r}
# Read ox data
df_sem_ox <- rio::import("rezultate_oxy+protT_sam_sem nov 2022.xlsx", which = "SEM") 
df_sem_ox <- df_sem_ox[, 2:5]
df_sem_ox <- 
  df_sem_ox %>% 
  janitor::clean_names() %>% 
  tidyr::separate_wider_delim(id_proba, delim = "/", names = c("id", "study", "prepost")) %>% 
  mutate(id = as.numeric(id))

# Join dataframes to add condition  - ! only elderly have ox
ids_ox_df <- ids_df[1:14, ]  # get only the elderly
df_sem_ox <- left_join(df_sem_ox, ids_ox_df, by = c("id" = "simple_id"))
```

# Stats

## SEM

```{r, fig.width=12, fig.height=6}
# A = baseline, B = 15min dupa OGL, C = 15 min dupa film

# A & B
df_sem_ox %>%
  filter(prepost %in% c("A", "B")) %>% 
  group_by(id, Cond) %>%
  filter(n() > 1) %>%                      # exclude incomplete
  ungroup() %>%
  ggstatsplot::grouped_ggwithinstats(
    x = prepost,
    y = oxitocina_normalizata,
    grouping.var = Cond, 
    type = "np",
    bf.message = FALSE,
    annotation.args = list(title = "Pre & Post OX data", subtitle = "Only A & B")
  )

# B & C
df_sem_ox %>%
  filter(prepost %in% c("B", "C")) %>% 
  group_by(id, Cond) %>%
  filter(n() > 1) %>%                      # exclude incomplete
  ungroup() %>%
  ggstatsplot::grouped_ggwithinstats(
    x = prepost,
    y = oxitocina_normalizata,
    grouping.var = Cond, 
    type = "np",
    bf.message = FALSE,
    annotation.args = list(title = "Pre & Post OX data", subtitle = "Only B & C")
  )

# A & B & C
df_sem_ox %>%
  # group_by(id, Cond) %>%
  # filter(n() > 1) %>%                      # exclude incomplete
  # ungroup() %>%
  ggstatsplot::grouped_ggwithinstats(
    x = prepost,
    y = oxitocina_normalizata,
    grouping.var = Cond, 
    pairwise.comparisons = FALSE,            # can't compare because not enough
    results.subtitle = FALSE,
    type = "np",
    bf.message = FALSE,
    annotation.args = list(title = "Pre & Post OX data", subtitle = "Full A & B & C")
  )
```



<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
