---
title: "<br> STAD SEM" 
subtitle: "Initial Analysis"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
            # toc: true
            # toc_depth: 2
            # number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include=FALSE}
# General R options
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation
options(repos = c(getOption("repos")["CRAN"], CRANextra = "https://mirror.clientvps.com/CRAN/"))  # use CRAN as default, set CRANextra to Nürnberg mirror


if (!require("pacman")) install.packages("pacman", dependencies = TRUE)
packages <- c(
  "papaja",
  "here", "fs",
  "conflicted",
  "rio",
  "tidyverse", 
  "psych",          
  "rstatix", "ggstatsplot",
  "ggplot2", "ggpubr", "scales",
  "report"
  # , ...
)
pacman::p_load(char = packages)

# Set here to Rnotebook directory
here::set_here()
unloadNamespace("here")                   # need new R session or unload namespace for .here file to take precedence over .Rproj
notebook_name <- fs::path_file(here::here())

# Solve conflicts in favor of tidyverse
conflicted::conflict_prefer("filter", winner = "dplyr")
conflicted::conflict_prefer("select", winner = "dplyr")
conflicted::conflict_prefer("slice", winner = "dplyr")
conflicted::conflict_prefer("rename", winner = "dplyr")
conflicted::conflict_prefer("count", winner = "dplyr")

# Set kintr options including root.dir pointing to the .here file in Rnotebook directory
knitr::opts_chunk$set(
  root.dir = here::here(),
  #fig.width = 5, fig.asp = 1/3, 
  comment = "#",
  collapse = TRUE,
  echo = TRUE, warning = TRUE, message = TRUE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# Themes for ggplot2 plotting (here used APA style)
theme_set(papaja::theme_apa())
```



<!-- Functions -->

# Define functions

```{r}
```


<!-- Report -->

# Read data

```{r, warning=FALSE, message=FALSE}
# Astea sunt datele scoase din taskul cu aranjarea screenshoturilor din filmul vizionat la SEM. Sunt aici toti participantii, si cei tineri, care nu au facut EEG (extensia lor de la ID este semc), si cei varstnici, care au si EEG (extensia lor e doar sem). Am adaugat in id si referinte la conditia experimentala, astfel ca cei care au ns in id au facut non-social (vizionat film singuri, fara sa faca Oglina), cei cu n sunt in conditia neutra (vizionat film cu o persoana straina alaturi, fara sa fi facut oglinda) si cei cu p au facut condizia pozitiva social (Oglinda si vizionarea filmului alaturi de instructor). Asa ca, de ex, al 10lea participant din lotul comportamental de tineri care a fost in grupul pozitiv social arata cam asa: 7semc p .
# In fisier gasesti datele scoase de computer in prima fila si pe a doua fila ai si genurile si varstele pt fiecare id. Sunt in ordinea cronologica, nu numerica. In prima fila am lasat si doua inregistrari facute ca probe pt ca mai aveau in partea din dreapta a tabelului niste date, ma gandesc ca poate au legatura cu modul de scorare, asa ca nu le-am sters.

ids_pattern_young <- ".*semc.*"
ids_pattern_old <- "^(?=.*sem)(?!.*semc).*$"    

# Stad
demo_df <- rio::import("taskmaginiSEM.xlsx", which = "Varsta-Gen")
demo_df$id <- tolower(trimws(demo_df$id))
sum(duplicated(demo_df$id)) == 0

stad_df <- rio::import("taskmaginiSEM.xlsx", which = "stad")
stad_df$id <- tolower(trimws(stad_df$id))

stad_df <-
  stad_df %>%
  select(-varsta, -gen) %>% 
  left_join(demo_df, by = "id") %>% 
  mutate(
    young = stringr::str_detect(id, ids_pattern_young),
    old = stringr::str_detect(id, ids_pattern_old)  
  ) %>% 
  separate(id, into = c("id2", "cond"), sep = " ", remove = FALSE) %>% 
  relocate(id, cond, varsta, gen, everything()) %>% 
  group_by(id) %>%
  mutate(trial_cycl = cumsum(c(1, diff(trialNo) < 0)))  %>%
  ungroup() %>%
  relocate(trial_cycl, .after = trialNo) %>%
  rowwise() %>%
  mutate(
    score = sum(
      correct1 == chosen1,
      correct2 == chosen2,
      correct3 == chosen3,
      correct4 == chosen4,
      correct5 == chosen5
    )          
  )

# stad_df %>%
#   filter(trial_cycl == 2) %>%
#   print(n = Inf)

stad_df %>%
  count(id, cond, varsta, gen) %>%
  print(n = Inf)
```

## Nonparametric

```{r, warning=FALSE, message=FALSE}
stad_df %>%
  filter(old) %>%
  group_by(id, cond) %>%
  summarise(score = sum(score)) %>%
  ungroup() %>% 
  ggstatsplot::ggbetweenstats(
    x = cond,
    y = score,
    outlier.label = id,
    type = "np",
    title = "Elderly"
  )

stad_df %>%
  filter(young) %>%
  group_by(id, cond) %>%
  summarise(score = sum(score)) %>%
  ungroup() %>% 
  ggstatsplot::ggbetweenstats(
    x = cond,
    y = score,
    outlier.label = id,
    type = "np",
    title = "General Sample"
  )
```

## Parametric

```{r, warning=FALSE, message=FALSE}
stad_df %>%
  filter(old) %>%
  group_by(id, cond) %>%
  summarise(score = sum(score)) %>%
  ungroup() %>% 
  ggstatsplot::ggbetweenstats(
    x = cond,
    y = score,
    outlier.label = id,
    type = "p",
    title = "Elderly"
  )

stad_df %>%
  filter(young) %>%
  group_by(id, cond) %>%
  summarise(score = sum(score)) %>%
  ungroup() %>% 
  ggstatsplot::ggbetweenstats(
    x = cond,
    y = score,
    outlier.label = id,
    type = "p",
    title = "General Sample"
  )
```



<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
