---
title: "<br> Ultimatum Game" 
subtitle: "Report"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
            # toc: true
            #  toc_depth: 2
            #  number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include=FALSE}
# kintr options
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  error = TRUE,
  echo = TRUE, warning = FALSE, message = FALSE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# General R options and info
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation

# Load packages
packages <- c(
  "papaja",
  "tidyverse",       
  "psych", "PerformanceAnalytics",          
  "summarytools", "tadaatoolbox",           
  "ggplot2", "ggpubr", "scales",        
  "rio",
  "rstatix", "broom", "emmeans", "pwr",
  "rlang",
  "performance", "DataExplorer", "ggstatsplot", "statsExpressions", "dlookr", "emmeans"
  # , ...
)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages, update = FALSE)

# Themes for ggplot2 ploting (here used APA style)
ggplot2::theme_set(papaja::theme_apa())
```



<!-- Report -->

```{r info, echo=FALSE, include=FALSE}
# INFO ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# UG 1:
#   https://agile-river-52629.herokuapp.com/
#   Download https://agile-river-52629.herokuapp.com/download/4twyt536wq
# UG 2:
#   https://tranquil-lowlands-63526.herokuapp.com/
#   Download: https://tranquil-lowlands-63526.herokuapp.com/download/4twyt536wq
# 
# 
# Analiza ANOVA 2X2 (Pre-Post X FairRate-UnfairRate)
# Folosim doar answer.csv (fiecare om trece prin 6 fair si 6 unfair)
# - Nu folosim alocator
# - Decident: unfair = 17-24 (6 oferte diferite); fair = 49-54 (6 oferte diferite) 
# - deci avem categ fair/unfair
# - Calc acceptance rate ... cate au fost acceptate pe fair, si cate pe unfair pt fiecare om in parte (deci 100% = 6 ca 6 traieluri sunt)
# - deci o sa avem un procentaj de acceptance pt fiecare om - una pe fair, una pe unfair
# - Calc media feedback ... cat e media fair pe fair, si pe unfair pt fiecare om in parte 
# - 0 = Deloc corect, 100 = Extrem de corect
# - deci o medie feedback pt fiecare om - una pe fair, una pe unfair
#
# verif: 
#   - fiecare are 6, exclus test run (bica.andreea21@gmail.com, ioana.r.podina@gmail.com, test@ro, rozetadraghici@gmail.com), 
# - outlier missmatch acceptance rate
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

# Read data

```{r read_data}
# Read in data ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setwd("E:/Cinetic idei noi/UG met")
pre <- readr::read_csv("PRE_answers.csv")
post <- readr::read_csv("POST_answers.csv")
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

# Emails and groups

```{r email_df}
# Read in data ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
setwd("C:/Users/Mihai/Desktop/R Notebooks/notebooks/UG-met")
email_df <- rio::import("mail-grup.xlsx", skip = 3)


gsr_df <- email_df[1:42, 1:4]
names(gsr_df)[1:4] <- c("Group", "Cond", "ID", "email")

rmn_df <- email_df[181:197, 2:4]
names(rmn_df)[1:3] <- c("Nr_Crt", "ID", "email")
rmn_df$Cond <- rep("EXPERIMENTAL", nrow(rmn_df))
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```


## Exclude known test-IDs

```{r filter}
# Exclude known test-IDs ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
excluded_id <- c("bica.andreea21@gmail.com", "ioana.r.podina@gmail.com", "test@ro", "rozetadraghici@gmail.com", "ioana.podina@fpse.unibuc.ro",
                 "cociaioana@gmail.com")

pre <-
  pre %>%
  dplyr::filter(!Username %in% excluded_id)

post <-
  post %>%
  dplyr::filter(!Username %in% excluded_id)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Check & Exclude IDs ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pre %>%
  count(Username) %>%
  print(n = Inf)   # "luciana.haloiu@invingemautismul.ro" has 24 trials instead of 12

post %>%
  count(Username) %>%
  print(n = Inf)   # all have 12 trials = is fine

pre <- 
  pre %>%
  dplyr::group_by(Username) %>%             # exclude last 12 trials of "luciana.haloiu@invingemautismul.ro"
  dplyr::filter(!(Username == "luciana.haloiu@invingemautismul.ro" & dplyr::row_number() %in% 13:24)) 
pre$Timestamp[pre$Username == "luciana.haloiu@invingemautismul.ro"]  # check: 12th trial is at "2020-11-23 16:40:59 UTC"

pre_ids <- data.frame(pre = unique(pre$Username))
post_ids <- data.frame(post = unique(post$Username))
list_ids <- dplyr::full_join(pre_ids, post_ids, by = c("pre" = "post"), keep = TRUE)
list_ids                   

complete_ids <-
  list_ids %>%
  tidyr::drop_na() %>%
  dplyr::mutate(pre = as.character(pre)) %>%
  dplyr::pull(pre)
  
# Keep only IDs that have both PRE and POST
pre <-
  pre %>%
  dplyr::filter(Username %in% complete_ids)

post <-
  post %>%
  dplyr::filter(Username %in% complete_ids)

```


# Compute scores

```{r scoring}
# Compute scores ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# utilizam doar Decident: unfair = 17-24 (6 oferte diferite); fair = 49-54 (6 oferte diferite)

# Define Fair/Unfair
pre <-
  pre %>%
  dplyr::mutate(Type = cut(Decident, breaks = c(-Inf, 30, Inf), labels = c("Unfair", "Fair")))

post <-
  post %>%
  dplyr::mutate(Type = cut(Decident, breaks = c(-Inf, 30, Inf), labels = c("Unfair", "Fair")))

# Compute Percent scores
pre_scores <-
  pre %>%
  dplyr::add_count(Username, Type, name = "n_Type") %>%
  dplyr::count(Username, Type, Accepted, n_Type, name = "n_Accepted_Type", .drop = FALSE) %>%   # need .drop = FALSE for missing factor levels leading to 0% Percentages
  dplyr::mutate(Percent = 100 * n_Accepted_Type / n_Type) %>%  
  dplyr::ungroup() %>%
  tidyr::complete(Username, Type, Accepted, fill = list(n_Type = 0, n_Accepted_Type = 0, Percent = 0)) %>%  # for missing factor levels leading to 0% Percentages
  dplyr::filter(Accepted == "Y") %>%
  dplyr::mutate(PrePost = rep("Pre", n())) %>%
  dplyr::mutate(PrePost= factor(PrePost, levels = c("Pre", "Post"))) 

post_scores <-
  post %>%
  dplyr::add_count(Username, Type, name = "n_Type") %>%
  dplyr::count(Username, Type, Accepted, n_Type, name = "n_Accepted_Type", .drop = FALSE) %>%   # need .drop = FALSE for missing factor levels leading to 0% Percentages
  dplyr::mutate(Percent = 100 * n_Accepted_Type / n_Type) %>%  
  dplyr::ungroup() %>%
  tidyr::complete(Username, Type, Accepted, fill = list(n_Type = 0, n_Accepted_Type = 0, Percent = 0)) %>%  # for missing factor levels leading to 0% Percentages
  dplyr::filter(Accepted == "Y") %>%
  dplyr::mutate(PrePost = rep("Post", n())) %>%
  dplyr::mutate(PrePost = factor(PrePost, levels = c("Pre", "Post")))
  

# Merge
merged_scores <- rbind(pre_scores, post_scores) 

merged_scores$Username <- tolower(merged_scores$Username)   # emails to lower letters to match on
gsr_df$email <- tolower(gsr_df$email)
rmn_df$email <- tolower(rmn_df$email)

merged_scores_gsr <- dplyr::left_join(merged_scores, gsr_df, by = c("Username" = "email"))     # Merge with emails/cond
merged_scores_rmn <- dplyr::left_join(merged_scores, rmn_df, by = c("Username" = "email"))     # Merge with emails/cond

merged_scores_gsr_rmn <-
  dplyr::left_join(merged_scores_gsr, merged_scores_rmn, by = c("Username", "Type", "Accepted", "n_Type", "n_Accepted_Type", "Percent", "PrePost")) %>%
  dplyr::mutate(Cond = dplyr::coalesce(Cond.x, Cond.y)) %>%
  dplyr::mutate(ID = dplyr::coalesce(ID.x, ID.y))

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Full scoring procedures but has problems with 0% cases (e.g. no Y answers for Fair ... this should be 0% but is not in data)
# This can be fixed in order to compute Percentages, but there is no way to fix it for Mean_Feedback because there is no Feedback for that combination
# pre_scores_df <-      
#   pre %>%
#   dplyr::add_count(Username, Type, name = "n_Type") %>%
#   dplyr::ungroup() %>%
#   dplyr::add_count(Username, Accepted, Type, name = "n_Accepted_Type") %>%
#   dplyr::mutate(Percent = 100 * n_Accepted_Type / n_Type) %>%
#   dplyr::ungroup() %>%
#   dplyr::group_by(Username, Accepted, Type) %>% 
#   dplyr::mutate(Mean_Feedback = mean(Feedback, na.rm = TRUE)) %>%  
#   dplyr::ungroup()
# 
# pre_scores <- 
#   pre_scores_df %>%
#   dplyr::group_by(Username, Accepted, Type, n_Type, n_Accepted_Type, Percent, Mean_Feedback) %>%
#   dplyr::summarise() %>%
#   dplyr::ungroup() %>%
#   dplyr::filter(Accepted == "Y") %>%
#   dplyr::mutate(PrePost = rep("Pre", n()))
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# Alternative scoring - DON'T USE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# pre_scores1 <-    # full scoring procedure, not excluding Unaccepted 
#   pre %>%
#   dplyr::group_by(Username, Type, Accepted) %>%
#   dplyr::summarise(n = n(), Mean_Feedback = mean(Feedback)) %>%
#   dplyr::mutate(Percent = n / 12)            # 12 is 100% of trials
# # rio::export(head(pre_scores1, 10), "ex1.xlsx")
# 
# pre_scores2 <-       # scoring procedure with exclusion of Unaccepted
#   pre %>%
#   dplyr::filter(Accepted == "Y") %>%
#   dplyr::group_by(Username, Type) %>%
#   dplyr::summarise(n = n(), Mean_Feedback = mean(Feedback)) %>%
#   dplyr::mutate(Percent = n / sum(n))  
# # rio::export(head(pre_scores2, 7), "ex2.xlsx")
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
  
```


# Two-way repeated measures ANOVA

```{r anova}
knitr::asis_output("## Analyses for Unfair")
merged_scores_gsr_unf <- 
  merged_scores_gsr %>%
  dplyr::filter(Type == "Unfair")

knitr::asis_output("### Descriptives")
merged_scores_gsr_unf %>%
  dplyr::group_by(Cond, PrePost) %>%
  rstatix::get_summary_stats(Percent, type = "mean_sd")

knitr::asis_output("### Outliers")
merged_scores_gsr_unf %>%
  dplyr::group_by(Cond, PrePost) %>%
  rstatix::identify_outliers(Percent)

knitr::asis_output("### Normality assumption")
merged_scores_gsr_unf %>%
  dplyr::group_by(Cond, PrePost) %>%
  rstatix::shapiro_test(Percent)

ggpubr::ggqqplot(merged_scores_gsr_unf, "Percent", ggtheme = theme_bw()) +
  ggplot2::facet_grid(PrePost ~ Cond)

knitr::asis_output("### ANOVA")
res_aov <- rstatix::anova_test(data = merged_scores_gsr_unf, dv = Percent, wid = Username, within = c(Cond, PrePost))
rstatix::get_anova_table(res_aov)

knitr::asis_output("### Pairwise comparisons between treatment groups")  
pwc <- 
  merged_scores_gsr_unf %>%
  dplyr::group_by(PrePost) %>%
  rstatix::pairwise_t_test(
    Percent ~ Cond, paired = TRUE,
    p.adjust.method = "bonferroni")
pwc

# Visualization: box plots with p-values
bxp <- ggpubr::ggboxplot(merged_scores_gsr_unf, x = "time", y = "score", color = "treatment", palette = "jco")
pwc <- pwc %>% add_xy_position(x = "PrePost")

bxp + 
  stat_pvalue_manual(pwc, tip.length = 0, hide.ns = TRUE) +
  labs(
    subtitle = get_test_label(res.aov, detailed = TRUE),
    caption = get_pwc_label(pwc)
  )  
```


# Plot

```{r plot, fig.height=7, fig.width=9, fig.sep=c('\\newline','\\newline'), warning=FALSE}
merged_scores_gsr_rmn %>%
    ggstatsplot::grouped_ggwithinstats(
      data = ., 
      x = PrePost,
      y = Percent,
      grouping.var = Type,
      type = "parametric",
      pairwise.comparisons = TRUE,
      pairwise.display = "all",
      annotation.args = list(title = "Whole Sample"))


merged_scores_gsr_rmn %>%
  dplyr::filter(Cond == "EXPERIMENTAL") %>%
    ggstatsplot::grouped_ggwithinstats(
      data = ., 
      x = PrePost,
      y = Percent,
      grouping.var = Type,
      type = "parametric",
      pairwise.comparisons = TRUE,
      pairwise.display = "all",
      annotation.args = list(title = "EXPERIMENTAL: PA4 + RMN"))

merged_scores_gsr_rmn %>%
  dplyr::filter(Cond == "EXPERIMENTAL", is.na(Nr_Crt)) %>%
    ggstatsplot::grouped_ggwithinstats(
      data = ., 
      x = PrePost,
      y = Percent,
      grouping.var = Type,
      type = "parametric",
      pairwise.comparisons = TRUE,
      pairwise.display = "all",
      annotation.args = list(title = "EXPERIMENTAL: PA4"))
  

merged_scores_gsr_rmn %>%
  dplyr::filter(Cond == "CONTROL") %>%
    grouped_ggwithinstats(
      data = ., 
      x = PrePost,
      y = Percent,
      grouping.var = Type,
      type = "parametric",
      pairwise.comparisons = TRUE,
      pairwise.display = "all",
      annotation.args = list(title = "CONTROL"))

merged_scores_gsr_rmn %>%
  dplyr::filter(!is.na(Nr_Crt)) %>%      # only RMN participants have Nr_Crt  
    ggstatsplot::grouped_ggwithinstats(
      data = ., 
      x = PrePost,
      y = Percent,
      grouping.var = Type,
      type = "parametric",
      pairwise.comparisons = TRUE,
      pairwise.display = "all",
      annotation.args = list(title = "EXPERIMENTAL: RMN"))
```





<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
