---
title: "<br> M2" 
subtitle: "Report"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
            # toc: true
            #  toc_depth: 2
            #  number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include=FALSE}
# kintr options
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  error = TRUE,
  echo = TRUE, warning = FALSE, message = FALSE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# General R options and info
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation

# Load packages
if (!require("pacman")) install.packages("pacman")
packages <- c(
  "papaja",
  "tidyverse",       
  "psych", "PerformanceAnalytics",          
  "broom", "rstatix",
  "summarytools", "tadaatoolbox",           
  "ggplot2", "ggpubr", "scales",        
  "rio",
  "ggpubr", "rstatix", "broom", "emmeans", "rlang"
  # , ...
)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages)

# Themes for ggplot2 ploting (here used APA style)
theme_set(theme_apa())
```





<!-- Report -->

# Define functions

```{r def_func}
## Define function that recodes to numeric, but watches out to coercion to not introduce NAs
colstonumeric <- function(df){
  tryCatch({
    df_num <- as.data.frame(
      lapply(df,
             function(x) { as.numeric(as.character(x))})) 
  },warning = function(stop_on_warning) {
    message("Stoped the execution of numeric conversion: ", conditionMessage(stop_on_warning))
  }) 
}
##
## Define function that reverse codes items
ReverseCode <- function(df, tonumeric = FALSE, min = NULL, max = NULL) {
  if(tonumeric) df <- colstonumeric(df)
  df <- (max + min) - df
}
##
## Define function that scores only rows with less than 10% NAs (returns NA if all or above threshold percentage of rows are NA); can reverse code if vector of column indexes and min, max are provided.
ScoreLikert <- function(df, napercent = .1, tonumeric = FALSE, reversecols = NULL, min = NULL, max = NULL) {
  reverse_list <- list(reversecols = reversecols, min = min, max = max)
  reverse_check <- !sapply(reverse_list, is.null)
  
  # Recode to numeric, but watch out to coercion to not introduce NAs
  colstonumeric <- function(df){
    tryCatch({
      df_num <- as.data.frame(
        lapply(df,
               function(x) { as.numeric(as.character(x))})) 
    },warning = function(stop_on_warning) {
      message("Stoped the execution of numeric conversion: ", conditionMessage(stop_on_warning))
    }) 
  }
  
  if(tonumeric) df <- colstonumeric(df)
  
  if(all(reverse_check)){
    df[ ,reversecols] <- (max + min) - df[ ,reversecols]
  }else if(any(reverse_check)){
    stop("Insuficient info for reversing. Please provide: ", paste(names(reverse_list)[!reverse_check], collapse = ", "))
  }
  
  ifelse(rowSums(is.na(df)) > ncol(df) * napercent,
         NA,
         rowSums(df, na.rm = TRUE) * NA ^ (rowSums(!is.na(df)) == 0)
  )
}
##
```


# Read, Clean, Recode

```{r read_clean_recode_merge, results='hide', message=FALSE}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Read, Clean, Recode, Unite
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

## Read files
folder <- "C:/Users/Mihai/Desktop/R Notebooks/notebooks/M2-report"
file <- "DateM2 final.xlsx"

setwd(folder)
Data_pre <- rio::import(file.path(folder, file),
                           skip = 3, which = "M2 PRE")

Data_post <- rio::import(file.path(folder, file),
                           skip = 3, which = "M2 POST")



# PRE = colnames(Data_pre); POST = colnames(Data_post) 
# cbind(PRE, POST)                                             # "s1.7" var is missing form POST -- missmatch row 12
#                                                              # also missing "s2.7" and others


# index from "DateM2.xlsx"
# index_ryff_pre <- 94:135
# index_pss_pre <- 136:149
# index_ryff_post <- 94:135 - 5
# index_pss_post <- 136:149 - 5

index_ryff_pre <- 83:124
index_pss_pre <- 125:138
index_ryff_post <- 81:122
index_pss_post <- 123:136


colnames(Data_pre)[1] <- "ID"
colnames(Data_pre)[colnames(Data_pre) == "Stres pre"] <- "VAS_stress_pre"
colnames(Data_pre)[colnames(Data_pre) == "Stres post"] <- "VAS_stress_post"
colnames(Data_pre)[index_ryff_pre] <- sprintf("ryff_%01d", seq(1, 42))
colnames(Data_pre)[index_pss_pre] <- sprintf("pss_%01d", seq(1, 14))
Data_pre <-
  Data_pre %>%
  drop_na(ID) %>%
  dplyr::mutate_if(is.character, list(~dplyr::na_if(., "na"))) 
Data_pre[index_ryff_pre] <- colstonumeric(Data_pre[index_ryff_pre])
Data_pre$pss_8[Data_pre$pss_8 == "++++++"] <- NA                           # typo
Data_pre[index_pss_pre] <- colstonumeric(Data_pre[index_pss_pre])

colnames(Data_post)[1] <- "ID"
colnames(Data_post)[colnames(Data_post) == "Stres pre"] <- "VAS_stress_pre"
colnames(Data_post)[colnames(Data_post) == "Stres post"] <- "VAS_stress_post"
colnames(Data_post)[index_ryff_post] <- sprintf("ryff_%01d", seq(1, 42))
colnames(Data_post)[index_pss_post] <- sprintf("pss_%01d", seq(1, 14))
Data_post <-
  Data_post %>%
  dplyr::mutate_if(is.character, list(~dplyr::na_if(., "na"))) 
Data_post[index_ryff_post] <- colstonumeric(Data_post[index_ryff_post])
Data_post[index_pss_post] <- colstonumeric(Data_post[index_pss_post])

# typos
# check_numeric <- as.data.frame(sapply(Data_pre[index_pss_pre], varhandle::check.numeric)) 
# sapply(check_numeric, function(x) length(which(!x)))

colnames(Data_pre)[colnames(Data_pre) == "s1.1."] <- "s1.1"
colnames(Data_post)[colnames(Data_post) == "s1.1."] <- "s1.1"

Data_post$s2.10[which(Data_post$s2.10 == ".")] <- NA
Data_post$s2.10 <- as.numeric(Data_post$s2.10)
Data_post$s3.16[which(Data_post$s3.16 == "kq")] <- NA
Data_post$s3.16 <- as.numeric(Data_post$s3.16)

```


```{r scoring, results='hide'}
## PSS-SF 14 (likert 0-4)
# Items 4, 5, 6, 7, 9, 10, and 13 are scored in reverse direction.

indexitem_revPSS <- c(4, 5, 6, 7, 9, 10, 13)

Data_pre[, index_pss_pre][indexitem_revPSS] <- ReverseCode(Data_pre[, index_pss_pre][indexitem_revPSS], tonumeric = FALSE, min = 0, max = 4)
Data_post[, index_pss_post][indexitem_revPSS] <- ReverseCode(Data_post[, index_pss_post][indexitem_revPSS], tonumeric = FALSE, min = 0, max = 4)

Data_pre$PSS <- ScoreLikert(Data_pre[, index_pss_pre], napercent = .4)
Data_post$PSS <- ScoreLikert(Data_post[, index_pss_post], napercent = .4)
  

## Ryff (likert 1-6)
# Recode negative phrased items:  3,5,10,13,14,15,16,17,18,19,23,26,27,30,31,32,34,36,39,41.
# Autonomy: 1,7,13,19,25,31,37
# Environmental mastery: 2,8,14,20,26,32,38
# Personal Growth: 3,9,15,21,27,33,39
# Positive Relations: 4,10,16,22,28,34,40
# Purpose in life: 5,11,17,23,29,35,41
# Self-acceptance: 6,12,18,24,30,36,42

indexitem_revRYFF <- c(3,5,10,13,14,15,16,17,18,19,23,26,27,30,31,32,34,36,39,41)

Data_pre[, index_ryff_pre][indexitem_revRYFF] <- ReverseCode(Data_pre[, index_ryff_pre][indexitem_revRYFF], tonumeric = FALSE, min = 1, max = 6)
Data_post[, index_ryff_post][indexitem_revRYFF] <- ReverseCode(Data_post[, index_ryff_post][indexitem_revRYFF], tonumeric = FALSE, min = 1, max = 6)

indexitem_Auto <- c(1,7,13,19,25,31,37)
indexitem_EnvM <- c(2,8,14,20,26,32,38)
indexitem_PersG <- c(3,9,15,21,27,33,39)
indexitem_PosRel <- c(4,10,16,22,28,34,40)
indexitem_PurLif <- c(5,11,17,23,29,35,41)
indexitem_SelfAc <- c(6,12,18,24,30,36,42)


Data_pre$Auto <- ScoreLikert(Data_pre[, index_ryff_pre][indexitem_Auto], napercent = .4)
Data_pre$EnvM <- ScoreLikert(Data_pre[, index_ryff_pre][indexitem_EnvM], napercent = .4)
Data_pre$PersG <- ScoreLikert(Data_pre[, index_ryff_pre][indexitem_PersG], napercent = .4)
Data_pre$PosRel <- ScoreLikert(Data_pre[, index_ryff_pre][indexitem_PosRel], napercent = .4)
Data_pre$PurLif <- ScoreLikert(Data_pre[, index_ryff_pre][indexitem_PurLif], napercent = .4)
Data_pre$SelfAc <- ScoreLikert(Data_pre[, index_ryff_pre][indexitem_SelfAc], napercent = .4)

Data_post$Auto <- ScoreLikert(Data_post[, index_ryff_post][indexitem_Auto], napercent = .4)
Data_post$EnvM <- ScoreLikert(Data_post[, index_ryff_post][indexitem_EnvM], napercent = .4)
Data_post$PersG <- ScoreLikert(Data_post[, index_ryff_post][indexitem_PersG], napercent = .4)
Data_post$PosRel <- ScoreLikert(Data_post[, index_ryff_post][indexitem_PosRel], napercent = .4)
Data_post$PurLif <- ScoreLikert(Data_post[, index_ryff_post][indexitem_PurLif], napercent = .4)
Data_post$SelfAc <- ScoreLikert(Data_post[, index_ryff_post][indexitem_SelfAc], napercent = .4)

## Save Scores
# rio::export(Data_pre[, c(1, 150:156)])
# rio::export(Data_post[, c(1, 149:155)])
# nlastcol <- 7
# rio::export(list(PRE = Data_pre[, c(1, (ncol(Data_pre)-nlastcol+1):ncol(Data_pre))], POST = Data_post[, c(1, (ncol(Data_post)-nlastcol+1):ncol(Data_post))]), 
#             "M2 PSS Ryff final.xlsx")

Data_pre$S1_Mean <- rowMeans(Data_pre[, sprintf("s1.%d", c(1:6, 8:16))], na.rm = TRUE)  # Data_pre[, grep("s1.", colnames(Data_pre))]
Data_pre$S2_Mean <- rowMeans(Data_pre[, sprintf("s2.%d", c(1:6, 8:16))], na.rm = TRUE)  # Data_pre[, grep("s2.", colnames(Data_pre))]
Data_pre$S3_Mean <- rowMeans(Data_pre[, sprintf("s3.%d", c(1:6, 8:16))], na.rm = TRUE)  # Data_pre[, grep("s3.", colnames(Data_pre))]

Data_post$S1_Mean <- rowMeans(Data_post[, sprintf("s1.%d", c(1:6, 8:16))], na.rm = TRUE)  # Data_post[, grep("s1.", colnames(Data_post))]
Data_post$S2_Mean <- rowMeans(Data_post[, sprintf("s2.%d", c(1:6, 8:16))], na.rm = TRUE)  # Data_post[, grep("s2.", colnames(Data_post))]
Data_post$S3_Mean <- rowMeans(Data_post[, sprintf("s3.%d", c(1:6, 8:16))], na.rm = TRUE)  # Data_post[, grep("s3.", colnames(Data_post))]
```


# Add TR & CTRL groups

```{r condgroups_df}
tr_ids <- paste0(c(1, 2, 4, 5, 6, 10, 13, 14, 15, 16, 24, 25, 26, 32, 34, 35, 39, 40, 42, 46, 47, 48, 51, 53, 59, 60, 62, 63, 64), " M2") 
ctrl_ids <- paste0(c(3, 7, 8, 9, 11, 12, 17, 18, 19, 20, 21, 22, 23, 27, 28, 30, 33, 36, 37, 38, 41, 43, 45, 49, 52, 54, 55, 56, 57, 58), " M2") 
# Subj from TR: Data_pre[which(Data_pre$ID %in% tr_ids),]  
# Subj from CTRL: Data_pre[which(Data_pre$ID %in% ctrl_ids),] 

Data_pre$Cond <- dplyr::case_when(Data_pre$ID %in% tr_ids ~ "TR",
                                  Data_pre$ID %in% ctrl_ids ~ "CTRL",
                                  TRUE ~ NA_character_)
Data_post$Cond <- dplyr::case_when(Data_post$ID %in% tr_ids ~ "TR",
                                  Data_post$ID %in% ctrl_ids ~ "CTRL",
                                  TRUE ~ NA_character_)
```


# Add Count-vars & Post-Vars

```{r post_vars}
names(Data_post)[137:139] <- c("spontaneous", "voluntary", "dreams")

Data_pre$s1.count <- rowSums(!is.na(Data_pre[, grepl("s1.*", names(Data_pre))]))
Data_pre$s2.count <- rowSums(!is.na(Data_pre[, grepl("s1.*", names(Data_pre))]))   
Data_pre$s3.count <- rowSums(!is.na(Data_pre[, grepl("s3.*", names(Data_pre))]))

Data_post$s1.count <- rowSums(!is.na(Data_post[, grepl("s1.*", names(Data_post))]))
Data_post$s2.count <- rowSums(!is.na(Data_post[, grepl("s1.*", names(Data_post))]))    # for some reason it has +1 count from all rest
Data_post$s3.count <- rowSums(!is.na(Data_post[, grepl("s3.*", names(Data_post))]))


# Added for M2 wide_format_4: mean_mem_age, count_ano
Data_pre$mean_mem_age <- rowMeans(Data_pre[, paste0("v", 1:16)], na.rm = TRUE)
Data_pre$count_iarna <- apply(Data_pre[, paste0("a", 1:16)], 1, function(x) length(which(x == "i")))
Data_pre$count_primvara <- apply(Data_pre[, paste0("a", 1:16)], 1, function(x) length(which(x == "p")))
Data_pre$count_vara <- apply(Data_pre[, paste0("a", 1:16)], 1, function(x) length(which(x == "v")))
Data_pre$count_toamna <- apply(Data_pre[, paste0("a", 1:16)], 1, function(x) length(which(x == "t")))

Data_post$mean_mem_age <- rowMeans(Data_post[, paste0("v", c(1:6, 8:16))], na.rm = TRUE)                  # missing v_7
Data_post$count_iarna <- apply(Data_post[, paste0("a", c(1:6, 8:16))], 1, function(x) length(which(x == "i")))
Data_post$count_primvara <- apply(Data_post[, paste0("a", c(1:6, 8:16))], 1, function(x) length(which(x == "p")))
Data_post$count_vara <- apply(Data_post[, paste0("a", c(1:6, 8:16))], 1, function(x) length(which(x == "v")))
Data_post$count_toamna <- apply(Data_post[, paste0("a", c(1:6, 8:16))], 1, function(x) length(which(x == "t")))
```



# Unite data frames

```{r unite_df}
cat("## Number of subjects in pre")
Data_pre %>% 
 dplyr::summarise(count = dplyr::n_distinct(ID))

cat("## Number of subjects in post")
Data_post %>%
 dplyr::summarise(count = dplyr::n_distinct(ID))

Data_pre$PrePost <- rep("Pre", nrow(Data_pre))
Data_post$PrePost <- rep("Post", nrow(Data_post))

Data_pre_scales <- Data_pre[, c("ID", "Varsta",
                                "VAS_stress_pre", "VAS_stress_post", "PSS", 
                                "Auto", "EnvM", "PersG", "PosRel", "PurLif",  "SelfAc", "S1_Mean", "S2_Mean", "S3_Mean", 
                                "PrePost", "Cond",
                                "s1.count", "s2.count", "s3.count", "mean_mem_age", "count_iarna", "count_primvara", "count_toamna")]
Data_post_scales <- Data_post[, c("ID", "Varsta",
                                  "VAS_stress_pre", "VAS_stress_post", "PSS", 
                                  "Auto", "EnvM", "PersG", "PosRel", "PurLif",  "SelfAc", "S1_Mean", "S2_Mean", "S3_Mean", 
                                  "PrePost", "Cond",
                                  "s1.count", "s2.count", "s3.count", "mean_mem_age", "count_iarna", "count_primvara", "count_toamna",
                                  "spontaneous", "voluntary", "dreams")]

Data_unif_long <- dplyr::bind_rows(Data_pre_scales, Data_post_scales)
Data_unif_wide <-
  Data_unif_long %>%
  tidyr::pivot_wider(id_cols = ID, names_from = PrePost, values_from = c(VAS_stress_pre, VAS_stress_post, PSS, Auto, EnvM, PersG, PosRel, PurLif, SelfAc, Cond,
                                                           S1_Mean, S2_Mean, S3_Mean, s1.count, s2.count, s3.count, spontaneous, voluntary, dreams,
                                                           mean_mem_age, count_iarna, count_primvara, count_toamna))

Data_unif_long <-
  Data_unif_long %>%
    dplyr::mutate(ID = as.factor(ID),
                  Cond = as.factor(Cond),
                  PrePost = as.factor(PrePost)) %>%
   dplyr::mutate(Vas_Diff = VAS_stress_post - VAS_stress_pre,
                 Vas_Mean = rowMeans(dplyr::select(.data = ., VAS_stress_post, VAS_stress_pre), na.rm = TRUE))


# saveRDS(Data_unif_wide, "M2 wide_format_4.RDS")

# Export data
# rio::export(Data_unif_wide, "M2 wide_format_2.xlsx")
# rio::export(Data_unif_long, "M2 long_format_2.xlsx")


# Export data for RMN in specified order
# rmn_order_ids <- paste0(c(1, 14, 13, 6, 4, 5, 10, 15, 2, 16, 42, 34, 24, 25, 26, 35, 39, 40, 32, 59, 53, 64, 46, 47, 62, 63, 48, 51, 60,
#                    8, 20, 12, 18, 9, 17, 19, 7, 3, 43, 41, 27, 23, 38, 22, 33, 28, 30, 21, 37, 49, 56, 58, 57, 52, 45, 55, 54), " ", "M2")
# 
# RMN_df <- Data_unif_wide[match(rmn_order_ids, Data_unif_wide$ID),]    # only 57 subjs for RMN
# 
# rio::export(RMN_df, "RMN ordered M2 wide_format_2.xlsx")
```


## Read NFkB

```{r read_nfkb, results='hide', message=FALSE}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Read, Clean, Recode, Unite
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

## Read files
folder <- "C:/Users/Mihai/Desktop/R Notebooks/notebooks/M2-report"
file <- "lista_M2 cu rezultate NFkB.xlsx"

setwd(folder)

Data_nfkb_TR <-  readxl::read_xlsx(file.path(folder, file), 
                                   range = "A1:F30", sheet = "NFkB")
Data_nfkb_CTRL <-  readxl::read_xlsx(file.path(folder, file), 
                                     range = "H1:M31", sheet = "NFkB")

Data_nfkb_TR <- Data_nfkb_TR[-1, ]
colnames(Data_nfkb_TR)[c(1, 4, 6)] <- c("ID", "NFkB_Pre", "NFkB_Post")
Data_nfkb_TR <- 
  Data_nfkb_TR %>%
  dplyr::rename_all(~stringr::str_replace_all(., " ", "_")) %>%
  dplyr::select(-starts_with("ID_Parhon")) %>%
  dplyr::mutate(Cond = rep("TR", nrow(Data_nfkb_TR))) %>%
  dplyr::mutate(ID = stringr::str_remove(ID, "ID")) %>%
  dplyr::mutate(ID = stringr::str_remove(ID, " ")) %>%
  dplyr::mutate(ID = stringr::str_c(ID, " M2"))
  

Data_nfkb_CTRL <- Data_nfkb_CTRL[-1, ]
colnames(Data_nfkb_CTRL)[c(1, 4, 6)] <- c("ID", "NFkB_Pre", "NFkB_Post")
Data_nfkb_CTRL <- 
  Data_nfkb_CTRL %>%
  dplyr::rename_all(~stringr::str_replace_all(., " ", "_")) %>%
  dplyr::select(-starts_with("ID_Parhon")) %>%
  dplyr::mutate(Cond = rep("CTRL", nrow(Data_nfkb_CTRL))) %>%
  dplyr::mutate(ID = stringr::str_remove(ID, "ID")) %>%
  dplyr::mutate(ID = stringr::str_remove(ID, " ")) %>%
  dplyr::mutate(ID = stringr::str_c(ID, " M2"))
```


# Unite with nfkb
```{r unite_df_nfkb}
# check
all.equal(colnames(Data_nfkb_TR), colnames(Data_nfkb_CTRL))

Data_unif_wide2 <- dplyr::left_join(Data_unif_wide, rbind(Data_nfkb_TR, Data_nfkb_CTRL), by = "ID")

# check
all.equal(Data_unif_wide2$Cond_Pre, Data_unif_wide2$Cond)

# saveRDS(Data_unif_wide2, "M2 wide_format_3.RDS") 
```



<!--
# NfKB
```{r nfkb_ttest}
func_t_box(Data_nfkb_TR, ind = "ID", pre_var = "NFkB_Pre", post_var = "NFkB_Post")

Data_nfkb_TR %>%
  tidyr::pivot_longer(cols = c(NFkB_Pre, NFkB_Post), names_to = "PrePost", values_to = "NFkB") %>%
  rstatix::wilcox_test(NFkB ~ PrePost, paired = TRUE) %>%
  rstatix::add_significance()

func_t_box(Data_nfkb_CTRL, ind = "ID", pre_var = "NFkB_Pre", post_var = "NFkB_Post")

Data_nfkb_CTRL %>%
  tidyr::pivot_longer(cols = c(NFkB_Pre, NFkB_Post), names_to = "PrePost", values_to = "NFkB") %>%
  rstatix::wilcox_test(NFkB ~ PrePost, paired = TRUE) %>%
  rstatix::add_significance()
```

## New Ideas: Correlations Number of memories & remembering

```{r cor_memory, fig.height=5, fig.height=6}
cat("PRE-POST Comparisons by Cond: TR")
Data_unif_long %>%
  dplyr::filter(Cond == "TR") %>% 
  rstatix::wilcox_test(s1.count ~ PrePost, paired = TRUE) %>%
  rstatix::add_significance()

cat("## PRE-POST Comparisons by Cond: CTRL")
Data_unif_long %>%
  dplyr::filter(Cond == "CTRL") %>% 
  rstatix::wilcox_test(s1.count ~ PrePost, paired = TRUE) %>%
  rstatix::add_significance()

cat("## POST-vars Comparisons by Cond")
Data_unif_long %>%
  dplyr::filter(PrePost == "Post") %>%
  rstatix::wilcox_test(s1.count ~ Cond, paired = FALSE) %>%
  rstatix::add_significance()

Data_unif_long %>%
  dplyr::filter(PrePost == "Post") %>% 
    rstatix::t_test(s1.count ~ Cond, paired = FALSE) %>%
    rstatix::add_significance()

Data_unif_long %>%
  dplyr::filter(PrePost == "Post") %>%
  rstatix::wilcox_test(voluntary ~ Cond, paired = FALSE) %>%
  rstatix::add_significance()                   

Data_unif_long %>%
  dplyr::filter(PrePost == "Post") %>%
    rstatix::t_test(voluntary ~ Cond, paired = FALSE) %>%
    rstatix::add_significance()

cat("## Correlation - whole sample")
Data_unif_long %>%
  dplyr::filter(PrePost == "Post") %>%
  dplyr::select(s1.count, spontaneous, voluntary, dreams) %>% 
  PerformanceAnalytics::chart.Correlation()

cat("## Correlation - TR")
Data_unif_long %>%
  dplyr::filter(PrePost == "Post") %>%
  dplyr::filter(Cond == "TR") %>%
  dplyr::select(s1.count, spontaneous, voluntary, dreams) %>% 
  PerformanceAnalytics::chart.Correlation()

cat("## Correlation - CTRL")
Data_unif_long %>%
  dplyr::filter(PrePost == "Post") %>%
  dplyr::filter(Cond == "CTRL") %>%
  dplyr::select(s1.count, spontaneous, voluntary, dreams) %>% 
  PerformanceAnalytics::chart.Correlation()
```

# Data in wide format

```{r}
Data_unif_wide2 %>%
  dplyr::select(-c(Nume_subiect, Cond)) %>%
    DT::datatable(
      extensions = 'Buttons',
      options = list(pageLength = 10,
                     scrollX='500px',
                     dom = 'Bfrtip',
                     buttons = c('excel', "csv")))

```
-->

<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
