---
title: "<br> O.4.c Repatate_psiho" 
subtitle: "Report"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
            # toc: true
            #  toc_depth: 2
            #  number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include=FALSE}
# kintr options
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  error = TRUE,
  echo = TRUE, warning = FALSE, message = FALSE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# General R options and info
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation

# Load packages
packages <- c(
  "papaja",
  "tidyverse",       
  "psych", "PerformanceAnalytics",          
  "summarytools", "tadaatoolbox",           
  "ggplot2", "ggpubr", "scales",        
  "rio",
  "rstatix", "broom", "emmeans", "pwr",
  "rlang",
  "performance", "DataExplorer", "ggstatsplot", "statsExpressions", "dlookr"
  # , ...
)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages, update = FALSE)

# Themes for ggplot2 ploting (here used APA style)
ggplot2::theme_set(papaja::theme_apa())
```





<!-- Report -->

# Read data

```{r}
Data <- rio::import("O.4 LongData.xlsx", skip = 1)   # data from O.4 Frontiers report in long format
Data <- Data[, -1]

# Select IDs from O.4.c study
subj_ids <-  c(7, 11, 14, 18, 19, 20, 21, 22, 23, 24, 25, 30, 31, 32, 34, 35, 38, 42, 56, 65)

Data <- 
  Data %>%
  dplyr::filter(ID %in% subj_ids)

# Transform
Data <-
  Data %>%
  dplyr::mutate(ID = as.factor(ID), 
                Gen = factor(Gen, levels = c("m", "f")),
                OglEcran = factor(OglEcran, levels = c("ECRAN", "OGL")),
                Nr_zi = factor(Nr_zi , levels = c(1, 2)),
                PrePost = factor(PrePost, levels = c("Pre", "Post")))

# Wide format
Data_wide <-
  Data %>%
  tidyr::pivot_wider(id_cols = c(1, 2:41), names_from = c(PrePost, OglEcran), values_from = c(43:44, 46:49))
```


## Dataset Long format

```{r}
Data %>%
    DT::datatable(
      extensions = 'Buttons',
      options = list(pageLength = 10,
                     scrollX='500px',
                     dom = 'Bfrtip',
                     buttons = c('excel', "csv")))
```

## Dataset Wide format

```{r}
Data_wide %>%
    DT::datatable(
      extensions = 'Buttons',
      options = list(pageLength = 10,
                     scrollX='500px',
                     dom = 'Bfrtip',
                     buttons = c('excel', "csv")))
```


# Depression

```{r, fig.height=6, fig.width=7, fig.sep=c('\\newline','\\newline')}
Data_wide %>%
  dplyr::mutate(BDI_d = factor(ifelse(ScorBDI > 29, 1, 0), levels = c(0, 1))) %>%
  ggplot(aes(x = ScorBDI, fill = BDI_d)) +
  geom_histogram(bins = 85, color = "black") +  
  geom_vline(xintercept = 14, colour = "red",  alpha = .8, size = .7, linetype = "dashed") +
  geom_vline(xintercept = 20, colour = "red",  alpha = .8, size = .7, linetype = "longdash") +
  geom_vline(xintercept = 29, colour = "red",  alpha = .8, size = .7) +
  scale_y_continuous(
    sec.axis = sec_axis(trans = ~./nrow(Data), labels = percent, 
                        name = "Proportie (%)")) +
  scale_fill_manual(breaks = c("0", "1"), 
                    values = wesanderson::wes_palette("Royal1")[1:2]) +
  ylab("Frecventa") +
  scale_x_continuous(breaks = seq(0, 30, by = 5)) +
  guides(fill = FALSE) +
  ggtitle("Niveluri de Depresie")
```  
  

# Anxiety

```{r, fig.height=6, fig.width=7, fig.sep=c('\\newline','\\newline')}
Data_wide %>%
  dplyr::mutate(StaiT_d = factor(ifelse(StaiTbrut > 30, 1, 0), levels = c(0, 1))) %>%
  ggplot(aes(x = StaiTbrut, fill = StaiT_d)) +
  geom_histogram(bins = 85, color = "black") +  
  geom_vline(xintercept = 10, colour = "red",  alpha = .8, size = .7, linetype = "dashed") +
  geom_vline(xintercept = 19, colour = "red",  alpha = .8, size = .7, linetype = "longdash") +
  geom_vline(xintercept = 30, colour = "red",  alpha = .8, size = .7) +
  scale_y_continuous(
    sec.axis = sec_axis(trans = ~./nrow(Data), labels = percent, 
                        name = "Proportie (%)")) +
  scale_fill_manual(breaks = c("0", "1"), 
                    values = wesanderson::wes_palette("Royal1")[1:2]) +
  ylab("Frecventa") +
  scale_x_continuous(breaks = seq(0, 65, by = 5)) +  # limits = c(0, 63)
  guides(fill = FALSE) +
  ggtitle("Niveluri de Anxietate")
``` 



# OXT

```{r, fig.height=7, fig.width=6, fig.sep=c('\\newline','\\newline')}
p_oxt_1 <- 
  Data %>%
    grouped_ggwithinstats(
      x = PrePost,
      y = OXT,
      grouping.var = OglEcran,
      type = "np", # non-parametric statistics
      xlab = "",
      outlier.tagging = TRUE,
      outlier.label = ID, 
      annotation.args = list(title = "Full dataset")) 

p_oxt_1
extract_stats(p_oxt_1)$subtitle_data

p_oxt_2 <-
  Data %>%
    dplyr::filter(!ID %in% c(19, 22)) %>%
      grouped_ggwithinstats(
      x = PrePost,
      y = OXT,
      grouping.var = OglEcran,
      type = "np", # non-parametric statistics
      xlab = "",
      outlier.tagging = TRUE,
      outlier.label = ID,
      annotation.args = list(title = "Outliers excluded"))

p_oxt_2
extract_stats(p_oxt_2)$subtitle_data
```


# IOS

```{r, fig.height=7, fig.width=6, fig.sep=c('\\newline','\\newline')}
p_ios_1 <- 
  Data %>%
    grouped_ggwithinstats(
      x = PrePost,
      y = IOS,
      grouping.var = OglEcran,
      type = "np", # non-parametric statistics
      xlab = "",
      outlier.tagging = TRUE,
      outlier.label = ID, 
      annotation.args = list(title = "Full dataset"))

p_ios_1
extract_stats(p_ios_1)$subtitle_data

# Data %>%
#   dplyr::filter(!ID %in% c(31)) %>%
#     grouped_ggwithinstats(
#     x = PrePost,
#     y = IOS,
#     grouping.var = OglEcran,
#     type = "np", # non-parametric statistics
#     xlab = "",
#     outlier.tagging = TRUE,
#     outlier.label = ID,
#     annotation.args = list(title = "Outliers excluded"))
```


# VAS Stress

```{r, fig.height=7, fig.width=6, fig.sep=c('\\newline','\\newline')}

p_vass_1 <- 
  Data %>%
    grouped_ggwithinstats(
      x = PrePost,
      y = Vas_Stres,
      grouping.var = OglEcran,
      type = "np", # non-parametric statistics
      xlab = "",
      outlier.tagging = TRUE,
      outlier.label = ID, 
      annotation.args = list(title = "Full dataset"))

p_vass_1
extract_stats(p_vass_1)$subtitle_data

p_vass_2 <-
  Data %>%
    dplyr::filter(!ID %in% c(19)) %>%
      grouped_ggwithinstats(
      x = PrePost,
      y = Vas_Stres,
      grouping.var = OglEcran,
      type = "np", # non-parametric statistics
      xlab = "",
      outlier.tagging = TRUE,
      outlier.label = ID,
      annotation.args = list(title = "Outliers excluded"))

p_vass_2
extract_stats(p_vass_2)$subtitle_data
```


# VAS Well-being

```{r, fig.height=7, fig.width=6, fig.sep=c('\\newline','\\newline')}
p_vasb_1 <- 
  Data %>%
    grouped_ggwithinstats(
      x = PrePost,
      y = Vas_Bine,
      grouping.var = OglEcran,
      type = "np", # non-parametric statistics
      xlab = "",
      outlier.tagging = TRUE,
      outlier.label = ID, 
      annotation.args = list(title = "Full dataset"))

p_vasb_1
extract_stats(p_vasb_1)$subtitle_data
```






<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
