---
title: "<br> O1B Pilot 11 subjects" 
subtitle: "Pilit data"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
            # toc: true
            #  toc_depth: 2
            #  number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include=FALSE}
# kintr options
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  echo = TRUE, warning = FALSE, message = TRUE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# General R options and info
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation

# Load packages
if (!require("pacman")) install.packages("pacman")
packages <- c(
  "papaja",
  "tidyverse", "plyr",      
  "psych", "PerformanceAnalytics",          
  "broom", "rstatix",
  "summarytools", "tadaatoolbox",           
  "ggplot2", "ggpubr", "scales",        
  "rio"
  # , ...
)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages)

# Themes for ggplot2 ploting (here used APA style)
theme_set(theme_apa())
```





<!-- Report -->


# Read, Clean, Recode, Merge

```{r red_clean_recode_merge, results='hide'}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Read, Clean, Recode, Unite
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

## Read files
folder <- "C:/Users/Mihai/Desktop/R Notebooks/notebooks/o1b-Pilot 11 sub"
file <- "DATE o1b 9IANUARIE2020.xlsx"

setwd(folder)
df_zi2 <- rio::import(file.path(folder, file),
                           which = "zi2",
                           skip = 1)

df_zi3 <- rio::import(file.path(folder, file),
                           which = "zi3",
                           skip = 0)

## Recode known missing values
df_zi2 <-
  df_zi2 %>%
  replace(. == "/", NA) %>%                                     # missing values are coded "/"
  replace(. == "-", NA) %>%                                     # missing values are coded "-"
  replace(. == "NA", NA)                                        # missing values are coded "NA"

df_zi3 <-
  df_zi3 %>%
  replace(. == "/", NA) %>%                                     # missing values are coded "/"
  replace(. == "-", NA) %>%                                     # missing values are coded "-"
  replace(. == "NA", NA)                                        # missing values are coded "NA"

## Filter out empty rows
df_zi2 <-
  df_zi2 %>%
  filter(!is.na(`ZI 2`))

df_zi3 <-
  df_zi3 %>%
  filter(!is.na(`ZI 3`))

```


```{r score_scales, results='hide'}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Recode and Score
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## StaiS
# Simple sum with reversed c(1,2,5,8,10,11,15,16,19,20)       min = 1; max = 4

# APS
# Simple sum.

## PANAS
# PA c(1,3,5,9,10,12,14,16,17,19)
# Na c(2,4,6,7,8,11,13,15,18,20)

## IRI
# Scales with reversed c(3,4,7,12,13,14,15,18,19)         min = 0; max = 4
# IRI_EC c(1,5,7,12,16,23,26)
# IRI_PT c(3,8,11,15,21,25,28)
# IRI_F c(2,4,9,14,18,20,22)
# IRI_PD c(6,10,13,17,19,24,27) 


## df_zi2
# pre PANAS 4:23
# pre APS 24:39
# pre STAIS 40:59
# pre IRI 62:89
# post PANAS 134:153
# post APS 154:169
# post STAIS 170:189
# post IRI 208:235

## df_zi3
# pre PANAS 4:23
# pre APS 24:39
# pre STAIS 40:59
# pre IRI 62:89
# post PANAS 125:144
# post APS 145:160
# post STAIS 161:180
# post IRI 199:226

names(df_zi2)[3] <- "Conditie"
names(df_zi3)[3] <- "Conditie"





## Define function that scores only rows with less than 10% NAs (returns NA if all or above threshold percentage of rows are NA); can reverse code if vector of column indexes and min, max are provided.
ScoreLikert <- function(df, napercent = .1, tonumeric = FALSE, reversecols = NULL, min = NULL, max = NULL) {
  reverse_list <- list(reversecols = reversecols, min = min, max = max)
  reverse_check <- !sapply(reverse_list, is.null)
  
  # Recode to numeric, but watch out to coercion to not introduce NAs
  colstonumeric <- function(df){
    tryCatch({
      df_num <- as.data.frame(
                    lapply(df,
                           function(x) { as.numeric(as.character(x))})) 
      },warning = function(stop_on_warning) {
        message("Stoped the execution of numeric conversion: ", conditionMessage(stop_on_warning))
    }) 
  }
  
  if(tonumeric) df <- colstonumeric(df)
  
  if(all(reverse_check)){
    df[ ,reversecols] <- (max + min) - df[ ,reversecols]
  }else if(any(reverse_check)){
    stop("Insuficient info for reversing. Please provide: ", paste(names(reverse_list)[!reverse_check], collapse = ", "))
  }
  
  ifelse(rowSums(is.na(df)) > ncol(df) * napercent,
         NA,
         rowSums(df, na.rm = TRUE) * NA ^ (rowSums(!is.na(df)) == 0)
  )
}


## Scoare some scales
# Zi 2
df_zi2$StaiS_pre <- ScoreLikert(df_zi2[, 40:59], reversecols = c(1,2,5,8,10,11,15,16,19,20), min = 1, max = 4)
df_zi2$StaiS_post <- ScoreLikert(df_zi2[, 181:200], reversecols = c(1,2,5,8,10,11,15,16,19,20), min = 1, max = 4)

df_zi2$PA_pre <- ScoreLikert(df_zi2[, 4:23][c(1,3,5,9,10,12,14,16,17,19)])
df_zi2$NA_pre <- ScoreLikert(df_zi2[, 4:23][c(2,4,6,7,8,11,13,15,18,20)])
df_zi2$PA_post <- ScoreLikert(df_zi2[, 134:153][c(1,3,5,9,10,12,14,16,17,19)])
df_zi2$NA_post <- ScoreLikert(df_zi2[, 134:153][c(2,4,6,7,8,11,13,15,18,20)]) 

df_zi2$APS_pre <- ScoreLikert(df_zi2[, 24:39])
df_zi2$APS_post <- ScoreLikert(df_zi2[, 154:169], tonumeric = T)

# Zi 3
df_zi3$StaiS_pre <- ScoreLikert(df_zi3[, 40:59], reversecols = c(1,2,5,8,10,11,15,16,19,20), min = 1, max = 4)
df_zi3$StaiS_post <- ScoreLikert(df_zi3[, 161:180], reversecols = c(1,2,5,8,10,11,15,16,19,20), min = 1, max = 4)

df_zi3$PA_pre <- ScoreLikert(df_zi3[, 4:23][c(1,3,5,9,10,12,14,16,17,19)])
df_zi3$NA_pre <- ScoreLikert(df_zi3[, 4:23][c(2,4,6,7,8,11,13,15,18,20)])
df_zi3$PA_post <- ScoreLikert(df_zi3[, 125:144][c(1,3,5,9,10,12,14,16,17,19)])
df_zi3$NA_post <- ScoreLikert(df_zi3[, 125:144][c(2,4,6,7,8,11,13,15,18,20)]) 

df_zi3$APS_pre <- ScoreLikert(df_zi3[, 24:39])
df_zi3$APS_post <- ScoreLikert(df_zi3[, 145:160])
```


## Extract by Condition

```{r cond, results='hide'}
jrad_zi2 <-
  df_zi2 %>%
  select(ID, Conditie, starts_with("StaiS_"), starts_with("PA_"), starts_with("NA_"), APS_pre, APS_post) %>%
  filter(Conditie == "JRAD")
jrad_zi3 <-
  df_zi3 %>%
  select(ID, Conditie, starts_with("StaiS_"), starts_with("PA_"), starts_with("NA_"), APS_pre, APS_post) %>%
  filter(Conditie == "JRAD")
jrad_df <- rbind(jrad_zi2, jrad_zi3)

es_zi2 <-
  df_zi2 %>%
  select(ID, Conditie, starts_with("StaiS_"), starts_with("PA_"), starts_with("NA_"), APS_pre, APS_post) %>%
  filter(Conditie == "ES")
es_zi3 <-
  df_zi3 %>%
  select(ID, Conditie, starts_with("StaiS_"), starts_with("PA_"), starts_with("NA_"), APS_pre, APS_post) %>%
  filter(Conditie == "ES")
es_df <- rbind(es_zi2, es_zi3)
```


# Define Function

```{r def_func, hide=TRUE}
## Func t test si boxplot simplu
func_t_box <- function(df, ind, pre_var, post_var){
  df_modif <-
    df %>%
    select(ind, pre_var, post_var) %>% 
    tidyr::drop_na() %>%
    gather(pre_var, post_var, key = "Cond", value = "value") %>% 
    mutate_at(vars(c(1, 2)), as.factor) %>% 
    mutate(Cond = factor(Cond, levels = c(pre_var, post_var))) 
  
  stat_comp <- ggpubr::compare_means(value ~ Cond, data = df_modif, method = "t.test", paired = TRUE)
  
  stat_comp2 <-
    df_modif %>% 
    do(tidy(t.test(.$value ~ .$Cond,
                   paired = TRUE,
                   data=.)))
  
  plot <- 
    ggpubr::ggpaired(df_modif, x = "Cond", y = "value", id = ind, 
                     color = "Cond", line.color = "gray", line.size = 0.4,
                     palette = c("#00AFBB", "#FC4E07"), legend = "none") +
      stat_summary(fun.data = mean_se,  colour = "darkred") +
      ggpubr::stat_compare_means(method = "t.test", paired = TRUE, label.x = as.numeric(df_modif$Cond)-0.4, label.y = max(df_modif$value)+0.5) + 
      ggpubr::stat_compare_means(method = "t.test", paired = TRUE, label = "p.signif", comparisons = list(c(pre_var, post_var)))
  
  cat(paste0("#### ", pre_var, " ", post_var, "\n", "\n"))
  print(stat_comp)
  print(stat_comp2)
  print(plot)
}
```



# Zi 2

```{r t_test_zi2, fig.width=5, fig.height=7, results='asis'}
cat("### JRAD")
func_t_box(jrad_df, "ID", "StaiS_pre", "StaiS_post")

func_t_box(jrad_df, "ID", "PA_pre", "PA_post")
func_t_box(jrad_df, "ID", "NA_pre", "NA_post")

func_t_box(jrad_df, "ID", "APS_pre", "APS_post")

cat("### ES")
func_t_box(es_df, "ID", "StaiS_pre", "StaiS_post")

func_t_box(es_df, "ID", "PA_pre", "PA_post")
func_t_box(es_df, "ID", "NA_pre", "NA_post")

func_t_box(es_df, "ID", "APS_pre", "APS_post")
```







<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
