---
title: "<br> O1B Report - behavioral" 
subtitle: "Initial Analysis"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    # pdf_document: 
            # toc: true
            #  toc_depth: 2
            #  number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include=FALSE}
# kintr options
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  echo = TRUE, warning = FALSE, message = TRUE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# General R options and info
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation

# Load packages
if (!require("pacman")) install.packages("pacman")
packages <- c(
  "papaja",
  "tidyverse", "plyr",      
  "psych", "PerformanceAnalytics",          
  "broom", "rstatix",
  "summarytools", "tadaatoolbox",           
  "ggplot2", "ggpubr", "scales",        
  "rio"
  # , ...
)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages)

# Themes for ggplot2 ploting (here used APA style)
theme_set(theme_apa())
```





<!-- Report -->


# Read, Clean, Recode, Merge

```{r red_clean_recode_merge, warning=FALSE, message=FALSE, results='hide',}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Read, Clean, Recode, Unite
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

## Read files

# Read current Data
folder <- "C:/Users/claud/Desktop/o1b-report-behavior"
file <- "DATE o1b A.xlsx"
setwd(folder)

suppressMessages({                                   # some columns are renamed and the warning breaks pandoc
df_zi2 <- rio::import(file.path(folder, file),
                           which = "zi2",
                           skip = 1)
})

suppressMessages({                                  # some columns are renamed and the warning breaks pandoc
df_zi3 <- rio::import(file.path(folder, file),
                           which = "zi3",
                           skip = 0)
})

## Check similarity with Pilot Data from xlsx
# folder_pilot <- "C:/Users/Mihai/Desktop/R Notebooks/notebooks/o1b-Pilot 11 sub"
# file_pilot <- "DATE o1b 9IANUARIE2020.xlsx"
# setwd(folder_pilot)
# 
# df_zi2_pilot <- rio::import(file.path(folder_pilot, file_pilot),
#                            which = "zi2",
#                            skip = 1)
# 
# df_zi3_pilot <- rio::import(file.path(folder_pilot, file_pilot),
#                            which = "zi3",
#                            skip = 0)
# 
# colnames(df_zi2) %in% colnames(df_zi2_pilot)
# which(colnames(df_zi2) %in% setdiff(colnames(df_zi2), colnames(df_zi2_pilot)))
# names(df_zi2[, c(24, 258, 368)]); names(df_zi2_pilot[, c(24, 258, 368)])    # zi2 mismatches @ col 24
# check <- data.frame(zi2 = colnames(df_zi2)[1:400], zi2_pilot = colnames(df_zi2_pilot)[1:400])  
# all.equal(df_zi2[, 23], df_zi2[, 24])    # col 23 and 24 are identical, but diffrent NA number -- keep 24, less NAs

df_zi2 <- df_zi2[, -23]    # exclude col 23 because 24 is the same with less NAs
df_zi2 <- df_zi2[, -258]   # exclude col 259 (258 after excluding 23) because it is empty
 
# all.equal(names(df_zi2), names(df_zi2_pilot))
# which(colnames(df_zi2) %in% setdiff(colnames(df_zi2), colnames(df_zi2_pilot)))
# names(df_zi2[, c(23, 257, 366)]); names(df_zi2_pilot[, c(23, 257, 366)])    # no more missmateches
# 
# colnames(df_zi3) %in% colnames(df_zi3_pilot)
# which(colnames(df_zi3) %in% setdiff(colnames(df_zi3), colnames(df_zi3_pilot)))
# names(df_zi3[, 141:144]); names(df_zi3_pilot[, 141:144])                     # so zi3 data si all the same, perfect match



## Recode known missing values
df_zi2 <-
  df_zi2 %>%
  replace(. == "/", NA) %>%                                     # missing values are coded "/"
  replace(. == "-", NA) %>%                                     # missing values are coded "-"
  replace(. == "NA", NA)                                        # missing values are coded "NA"

df_zi3 <-
  df_zi3 %>%
  replace(. == "/", NA) %>%                                     # missing values are coded "/"
  replace(. == "-", NA) %>%                                     # missing values are coded "-"
  replace(. == "NA", NA)                                        # missing values are coded "NA"

## Filter out empty rows
df_zi2 <-
  df_zi2 %>%
  filter(!is.na(`ZI 2`))

df_zi3 <-
  df_zi3 %>%
  filter(!is.na(`ZI 3`))

```


```{r score_scales, results='hide'}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Recode and Score
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## StaiS
# Simple sum with reversed c(1,2,5,8,10,11,15,16,19,20)       min = 1; max = 4

# APS
# Simple sum.

## PANAS
# PA c(1,3,5,9,10,12,14,16,17,19)
# Na c(2,4,6,7,8,11,13,15,18,20)

## IRI
# --- in xlsx responses are A,B,C,D,E
# Scales with reversed c(3,4,7,12,13,14,15,18,19)         min = 0; max = 4
# IRI_EC c(1,5,7,12,16,23,26)
# IRI_PT c(3,8,11,15,21,25,28)
# IRI_F c(2,4,9,14,18,20,22)
# IRI_PD c(6,10,13,17,19,24,27) 

## Rosenberg
# --- in xlsx responses are registerd correctly (0-3)
# Simple sum with reversed c(2,5,6,8,9)       min = 0; max = 3


## df_zi2  (attention: all relevenat data is col < 257; part of zi3 is doubled in the sheet for zi2)
# pre PANAS 4:23
# pre APS 24:39
# pre STAIS 40:59
# pre IRI 62:89
# pre Rosenberg 101:110
# post PANAS 134:153
# post APS 154:169
# post STAIS 170:189
# post IRI 208:235
# post Rosenberg 236:245

## df_zi3
# pre PANAS 4:23
# pre APS 24:39
# pre STAIS 40:59
# pre IRI 62:89
# pre Rosenberg 101:110
# post PANAS 125:144
# post APS 145:160
# post STAIS 161:180
# post IRI 199:226
# post Rosenberg 227:236

names(df_zi2)[3] <- "Conditie"
names(df_zi3)[3] <- "Conditie"

names(df_zi2)[grepl("IOS", names(df_zi2))][1] <- "IOS"
names(df_zi3)[grepl("IOS", names(df_zi3))][1] <- "IOS"

df_zi2[20, 57] <- 1  # correct typos
df_zi2[22, 49] <- 1
df_zi3[13, 126] <- 1
df_zi3[14, 126] <- 1
df_zi3[15, 126] <- 1

df_zi3[29, 40] <- 1
df_zi3[29, 41] <- 2
  
## Define function that recodes to numeric, but watches out to coercion to not introduce NAs
colstonumeric <- function(df){
  tryCatch({
    df_num <- as.data.frame(
      lapply(df,
             function(x) { as.numeric(as.character(x))})) 
  },warning = function(stop_on_warning) {
    message("Stoped the execution of numeric conversion: ", conditionMessage(stop_on_warning))
  }) 
}

## Define function that scores only rows with less than 10% NAs (returns NA if all or above threshold percentage of rows are NA); can reverse code if vector of column indexes and min, max are provided.
ScoreLikert <- function(df, napercent = .1, tonumeric = FALSE, reversecols = NULL, min = NULL, max = NULL) {
  reverse_list <- list(reversecols = reversecols, min = min, max = max)
  reverse_check <- !sapply(reverse_list, is.null)
  
  # Recode to numeric, but watch out to coercion to not introduce NAs
  colstonumeric <- function(df){
    tryCatch({
      df_num <- as.data.frame(
                    lapply(df,
                           function(x) { as.numeric(as.character(x))})) 
      },warning = function(stop_on_warning) {
        message("Stoped the execution of numeric conversion: ", conditionMessage(stop_on_warning))
    }) 
  }
  
  if(tonumeric) df <- colstonumeric(df)
  
  if(all(reverse_check)){
    df[ ,reversecols] <- (max + min) - df[ ,reversecols]
  }else if(any(reverse_check)){
    stop("Insuficient info for reversing. Please provide: ", paste(names(reverse_list)[!reverse_check], collapse = ", "))
  }
  
  ifelse(rowSums(is.na(df)) > ncol(df) * napercent,
         NA,
         rowSums(df, na.rm = TRUE) * NA ^ (rowSums(!is.na(df)) == 0)
  )
}


# Recode responses for IRI (both datasets + recode)
indexitemIRI_df_zi2_pre <- 62:89
indexitemIRI_df_zi2_post <- 208:235
indexitemIRI_df_zi2 <- c(62:89, 208:235)                    # pre & post
df_zi2[ ,indexitemIRI_df_zi2] [with(df_zi2[ ,indexitemIRI_df_zi2], df_zi2[ ,indexitemIRI_df_zi2] == "a" | 
                                        df_zi2[ ,indexitemIRI_df_zi2] == "A")] <- 0
df_zi2[ ,indexitemIRI_df_zi2] [with(df_zi2[ ,indexitemIRI_df_zi2], df_zi2[ ,indexitemIRI_df_zi2] == "b" | 
                                        df_zi2[ ,indexitemIRI_df_zi2] == "B")] <- 1
df_zi2[ ,indexitemIRI_df_zi2] [with(df_zi2[ ,indexitemIRI_df_zi2], df_zi2[ ,indexitemIRI_df_zi2] == "c" | 
                                        df_zi2[ ,indexitemIRI_df_zi2] == "C")] <- 2
df_zi2[ ,indexitemIRI_df_zi2] [with(df_zi2[ ,indexitemIRI_df_zi2], df_zi2[ ,indexitemIRI_df_zi2] == "d" | 
                                        df_zi2[ ,indexitemIRI_df_zi2] == "D")] <- 3
df_zi2[ ,indexitemIRI_df_zi2] [with(df_zi2[ ,indexitemIRI_df_zi2], df_zi2[ ,indexitemIRI_df_zi2] == "e" | 
                                        df_zi2[ ,indexitemIRI_df_zi2] == "E")] <- 4
df_zi2[, indexitemIRI_df_zi2_pre][c(3,4,7,12,13,14,15,18,19)] <- 4 - colstonumeric(df_zi2[, indexitemIRI_df_zi2_pre][c(3,4,7,12,13,14,15,18,19)])   # reverse code
df_zi2[, indexitemIRI_df_zi2_post][c(3,4,7,12,13,14,15,18,19)] <- 4 - colstonumeric(df_zi2[, indexitemIRI_df_zi2_post][c(3,4,7,12,13,14,15,18,19)])

indexitemIRI_df_zi3_pre <- 62:89
indexitemIRI_df_zi3_post <- 199:226
indexitemIRI_df_zi3 <- c(62:89, 199:226)                    # pre & post
df_zi3[ ,indexitemIRI_df_zi3] [with(df_zi3[ ,indexitemIRI_df_zi3], df_zi3[ ,indexitemIRI_df_zi3] == "a" | 
                                      df_zi3[ ,indexitemIRI_df_zi3] == "A")] <- 0
df_zi3[ ,indexitemIRI_df_zi3] [with(df_zi3[ ,indexitemIRI_df_zi3], df_zi3[ ,indexitemIRI_df_zi3] == "b" | 
                                      df_zi3[ ,indexitemIRI_df_zi3] == "B")] <- 1
df_zi3[ ,indexitemIRI_df_zi3] [with(df_zi3[ ,indexitemIRI_df_zi3], df_zi3[ ,indexitemIRI_df_zi3] == "c" | 
                                      df_zi3[ ,indexitemIRI_df_zi3] == "C")] <- 2
df_zi3[ ,indexitemIRI_df_zi3] [with(df_zi3[ ,indexitemIRI_df_zi3], df_zi3[ ,indexitemIRI_df_zi3] == "d" | 
                                      df_zi3[ ,indexitemIRI_df_zi3] == "D")] <- 3
df_zi3[ ,indexitemIRI_df_zi3] [with(df_zi3[ ,indexitemIRI_df_zi3], df_zi3[ ,indexitemIRI_df_zi3] == "e" | 
                                      df_zi3[ ,indexitemIRI_df_zi3] == "E")] <- 4
df_zi3[, indexitemIRI_df_zi3_pre][c(3,4,7,12,13,14,15,18,19)] <- 4 - colstonumeric(df_zi3[, indexitemIRI_df_zi3_pre][c(3,4,7,12,13,14,15,18,19)])   # reverse code
df_zi3[, indexitemIRI_df_zi3_post][c(3,4,7,12,13,14,15,18,19)] <- 4 - colstonumeric(df_zi3[, indexitemIRI_df_zi3_post][c(3,4,7,12,13,14,15,18,19)])



## Scoring scales  -- GRESEALA StaiS_post index 170:189
# Zi 2
df_zi2$StaiS_pre <- ScoreLikert(df_zi2[, 40:59], reversecols = c(1,2,5,8,10,11,15,16,19,20), tonumeric = TRUE, min = 1, max = 4)
df_zi2$StaiS_post <- ScoreLikert(df_zi2[, 170:189], reversecols = c(1,2,5,8,10,11,15,16,19,20), tonumeric = TRUE, min = 1, max = 4)

df_zi2$PA_pre <- ScoreLikert(df_zi2[, 4:23][c(1,3,5,9,10,12,14,16,17,19)], tonumeric = TRUE,)
df_zi2$NA_pre <- ScoreLikert(df_zi2[, 4:23][c(2,4,6,7,8,11,13,15,18,20)], tonumeric = TRUE,)
df_zi2$PA_post <- ScoreLikert(df_zi2[, 134:153][c(1,3,5,9,10,12,14,16,17,19)], tonumeric = TRUE,)
df_zi2$NA_post <- ScoreLikert(df_zi2[, 134:153][c(2,4,6,7,8,11,13,15,18,20)], tonumeric = TRUE,) 

df_zi2$APS_pre <- ScoreLikert(df_zi2[, 24:39], tonumeric = TRUE)
df_zi2$APS_post <- ScoreLikert(df_zi2[, 154:169], tonumeric = TRUE)

df_zi2$Rosenberg_pre <- ScoreLikert(df_zi2[, 101:110], reversecols = c(2,5,6,8,9), napercent = .5, tonumeric = TRUE, min = 0, max = 3)
df_zi2$Rosenberg_post <- ScoreLikert(df_zi2[, 236:245], reversecols = c(2,5,6,8,9), napercent = .5, tonumeric = TRUE, min = 0, max = 3)

df_zi2$IRI_EC_pre <- ScoreLikert(df_zi2[, 62:89][c(1,5,7,12,16,23,26)], napercent = .5, tonumeric = TRUE)
df_zi2$IRI_PT_pre <- ScoreLikert(df_zi2[, 62:89][c(3,8,11,15,21,25,28)], napercent = .5, tonumeric = TRUE)
df_zi2$IRI_F_pre <- ScoreLikert(df_zi2[, 62:89][c(2,4,9,14,18,20,22)], napercent = .5, tonumeric = TRUE)
df_zi2$IRI_PD_pre <- ScoreLikert(df_zi2[, 62:89][c(6,10,13,17,19,24,27)], napercent = .5, tonumeric = TRUE)

df_zi2$IRI_EC_post <- ScoreLikert(df_zi2[, 208:235][c(1,5,7,12,16,23,26)], napercent = .5, tonumeric = TRUE)
df_zi2$IRI_PT_post <- ScoreLikert(df_zi2[, 208:235][c(3,8,11,15,21,25,28)], napercent = .5, tonumeric = TRUE)
df_zi2$IRI_F_post <- ScoreLikert(df_zi2[, 208:235][c(2,4,9,14,18,20,22)], napercent = .5, tonumeric = TRUE)
df_zi2$IRI_PD_post<- ScoreLikert(df_zi2[, 208:235][c(6,10,13,17,19,24,27)], napercent = .5, tonumeric = TRUE)


# Zi 3
df_zi3[, 162]

df_zi3$StaiS_pre <- ScoreLikert(df_zi3[, 40:59], reversecols = c(1,2,5,8,10,11,15,16,19,20), tonumeric = TRUE, min = 1, max = 4)
df_zi3$StaiS_post <- ScoreLikert(df_zi3[, 161:180], reversecols = c(1,2,5,8,10,11,15,16,19,20), tonumeric = TRUE, min = 1, max = 4)

df_zi3$PA_pre <- ScoreLikert(df_zi3[, 4:23][c(1,3,5,9,10,12,14,16,17,19)], tonumeric = TRUE,)
df_zi3$NA_pre <- ScoreLikert(df_zi3[, 4:23][c(2,4,6,7,8,11,13,15,18,20)], tonumeric = TRUE,)
df_zi3$PA_post <- ScoreLikert(df_zi3[, 125:144][c(1,3,5,9,10,12,14,16,17,19)], tonumeric = TRUE,)
df_zi3$NA_post <- ScoreLikert(df_zi3[, 125:144][c(2,4,6,7,8,11,13,15,18,20)], tonumeric = TRUE,) 

df_zi3$APS_pre <- ScoreLikert(df_zi3[, 24:39], tonumeric = TRUE)
df_zi3$APS_post <- ScoreLikert(df_zi3[, 145:160], tonumeric = TRUE)

df_zi3$Rosenberg_pre <- ScoreLikert(df_zi3[, 101:110], reversecols = c(2,5,6,8,9), napercent = .5, tonumeric = TRUE, min = 0, max = 3)
df_zi3$Rosenberg_post <- ScoreLikert(df_zi3[, 227:236], reversecols = c(2,5,6,8,9), napercent = .5, tonumeric = TRUE, min = 0, max = 3)

df_zi3$IRI_EC_pre <- ScoreLikert(df_zi3[, 62:89][c(1,5,7,12,16,23,26)], napercent = .5, tonumeric = TRUE)
df_zi3$IRI_PT_pre <- ScoreLikert(df_zi3[, 62:89][c(3,8,11,15,21,25,28)], napercent = .5, tonumeric = TRUE)
df_zi3$IRI_F_pre <- ScoreLikert(df_zi3[, 62:89][c(2,4,9,14,18,20,22)], napercent = .5, tonumeric = TRUE)
df_zi3$IRI_PD_pre <- ScoreLikert(df_zi3[, 62:89][c(6,10,13,17,19,24,27)], napercent = .5, tonumeric = TRUE)

df_zi3$IRI_EC_post <- ScoreLikert(df_zi3[, 199:226][c(1,5,7,12,16,23,26)], napercent = .5, tonumeric = TRUE)
df_zi3$IRI_PT_post <- ScoreLikert(df_zi3[, 199:226][c(3,8,11,15,21,25,28)], napercent = .5, tonumeric = TRUE)
df_zi3$IRI_F_post <- ScoreLikert(df_zi3[, 199:226][c(2,4,9,14,18,20,22)], napercent = .5, tonumeric = TRUE)
df_zi3$IRI_PD_post<- ScoreLikert(df_zi3[, 199:226][c(6,10,13,17,19,24,27)], napercent = .5, tonumeric = TRUE)

```


## Extract by Condition

```{r cond, results='hide'}
jrad_zi2 <-
  df_zi2 %>%
  select(ID, Conditie, starts_with("StaiS_"), starts_with("PA_"), starts_with("NA_"), 
         APS_pre, APS_post,
         Rosenberg_pre, Rosenberg_post,
         IRI_EC_pre, IRI_EC_post,
         IRI_PT_pre, IRI_PT_post,
         IRI_F_pre, IRI_F_post,
         IRI_PD_pre, IRI_PD_post,
         IOS
         ) %>%
  filter(Conditie == "JRAD")
jrad_zi3 <-
  df_zi3 %>%
  select(ID, Conditie, starts_with("StaiS_"), starts_with("PA_"), starts_with("NA_"), 
         APS_pre, APS_post,
         Rosenberg_pre, Rosenberg_post,
         IRI_EC_pre, IRI_EC_post,
         IRI_PT_pre, IRI_PT_post,
         IRI_F_pre, IRI_F_post,
         IRI_PD_pre, IRI_PD_post,
         IOS
         ) %>%
  filter(Conditie == "JRAD")
jrad_df <- rbind(jrad_zi2, jrad_zi3)

es_zi2 <-
  df_zi2 %>%
   select(ID, Conditie, starts_with("StaiS_"), starts_with("PA_"), starts_with("NA_"), 
         APS_pre, APS_post,
         Rosenberg_pre, Rosenberg_post,
         IRI_EC_pre, IRI_EC_post,
         IRI_PT_pre, IRI_PT_post,
         IRI_F_pre, IRI_F_post,
         IRI_PD_pre, IRI_PD_post,
         IOS
         ) %>%
  filter(Conditie == "ES")
es_zi3 <-
  df_zi3 %>%
   select(ID, Conditie, starts_with("StaiS_"), starts_with("PA_"), starts_with("NA_"), 
         APS_pre, APS_post,
         Rosenberg_pre, Rosenberg_post,
         IRI_EC_pre, IRI_EC_post,
         IRI_PT_pre, IRI_PT_post,
         IRI_F_pre, IRI_F_post,
         IRI_PD_pre, IRI_PD_post,
         IOS
         ) %>%
  filter(Conditie == "ES")
es_df <- rbind(es_zi2, es_zi3)
```


# Define Function

```{r def_func, hide=TRUE}
## Func t test si boxplot simplu
func_t_box <- function(df, ind, pre_var, post_var){
  vars <- c(ind, pre_var, post_var)                # to avoid new tidyverse error of ambiguity due to external vectos
  df_modif <-
    df %>%
    dplyr::select(tidyselect::all_of(vars)) %>% 
    tidyr::drop_na() %>%
    gather(tidyselect::all_of(pre_var), tidyselect::all_of(post_var), key = "Cond", value = "value") %>% 
    mutate_at(vars(c(1, 2)), as.factor) %>% 
    mutate(Cond = factor(Cond, levels = c(pre_var, post_var))) 
  
  stat_comp <- ggpubr::compare_means(value ~ Cond, data = df_modif, method = "t.test", paired = TRUE)
  
  stat_comp2 <-
    df_modif %>% 
    do(tidy(t.test(.$value ~ .$Cond,
                   paired = TRUE,
                   data=.)))
  
  plot <- 
    ggpubr::ggpaired(df_modif, x = "Cond", y = "value", id = ind, 
                     color = "Cond", line.color = "gray", line.size = 0.4,
                     palette = c("#00AFBB", "#FC4E07"), legend = "none") +
      stat_summary(fun.data = mean_se,  colour = "darkred") +
      ggpubr::stat_compare_means(method = "t.test", paired = TRUE, label.x = as.numeric(df_modif$Cond)-0.4, label.y = max(df_modif$value)+0.5) + 
      ggpubr::stat_compare_means(method = "t.test", paired = TRUE, label = "p.signif", comparisons = list(c(pre_var, post_var)))
  
  cat(paste0("#### ", pre_var, " ", post_var, "\n", "\n"))
  print(stat_comp)
  print(stat_comp2)
  print(plot)
}
```



# Initial Analyses

```{r t_test, fig.width=5, fig.height=7, results='asis', warning=FALSE}
cat("### JRAD")
func_t_box(jrad_df, "ID", "StaiS_pre", "StaiS_post")

func_t_box(jrad_df, "ID", "PA_pre", "PA_post")
func_t_box(jrad_df, "ID", "NA_pre", "NA_post")

func_t_box(jrad_df, "ID", "APS_pre", "APS_post")

func_t_box(jrad_df, "ID", "Rosenberg_pre", "Rosenberg_post")

func_t_box(jrad_df, "ID", "IRI_EC_pre", "IRI_EC_post")
func_t_box(jrad_df, "ID", "IRI_PT_pre", "IRI_PT_post")
func_t_box(jrad_df, "ID", "IRI_F_pre", "IRI_F_post")
func_t_box(jrad_df, "ID", "IRI_PD_pre", "IRI_PD_post")
         

cat("### ES")
func_t_box(es_df, "ID", "StaiS_pre", "StaiS_post")

func_t_box(es_df, "ID", "PA_pre", "PA_post")
func_t_box(es_df, "ID", "NA_pre", "NA_post")

func_t_box(es_df, "ID", "APS_pre", "APS_post")

func_t_box(es_df, "ID", "Rosenberg_pre", "Rosenberg_post")

func_t_box(es_df, "ID", "IRI_EC_pre", "IRI_EC_post")
func_t_box(es_df, "ID", "IRI_PT_pre", "IRI_PT_post")
func_t_box(es_df, "ID", "IRI_F_pre", "IRI_F_post")
func_t_box(es_df, "ID", "IRI_PD_pre", "IRI_PD_post")
```


# JRAD - Prez

```{r}
plot_STAI_jrad <- 
  jrad_df %>%
    dplyr::select(ID, StaiS_pre, StaiS_post) %>%
    tidyr::pivot_longer(cols = c(StaiS_pre, StaiS_post), names_to = "Time", values_to = "value") %>%
    dplyr::mutate(
      Time = stringr::str_replace(Time, "pre", "Pre"),
      Time = stringr::str_replace(Time, "post", "Post"), 
      Time = stringr::str_remove(Time, ".*_"),
      Time = stringr::str_remove(Time, "_"), 
      Time = factor(Time, levels = c("Pre", "Post"))) %>%
    group_by(ID) %>%
    ggstatsplot::ggwithinstats(
      x = Time,
      y = value,
      title = "Anxiety",
      xlab = "Time",
      ylab = "Anxiety",
      pairwise.comparisons = TRUE,
      pairwise.display = "significant",
      results.subtitle = TRUE,
      type = "parametric",
      bf.message = FALSE, 
      p.adjust.method = "none",
      point.path = TRUE,
      outlier.tagging = FALSE,
      ggtheme = ggprism::theme_prism(),
      # package = "RColorBrewer",  # "ggsci",
      # palette = "Dark",         # "default_jco",
      violin.args = list(width = 0.9, alpha = 0.2, size = 1, color = "black"),
      centrality.point.args = list(size = 5, color = "darkred"),
      centrality.label.args = list(size = 3, nudge_x = 0.2, segment.linetype = 5, fill = "#FFF8E7"), 
      ggplot.component = list(
        theme(
          plot.title = element_text(hjust = 0, size = 16),
          plot.subtitle = element_text(hjust = 0, size = 12), 
          plot.caption = element_text(hjust = 0, size = 12), 
          text = element_text(size = 14)
      ))
    ) + scale_colour_grey(start = 0.2, end = 0.2)   # hacky way to change point color

ggsave(plot_STAI_jrad, 
       filename = "StaiS JRAD.png", 
       height = 8, width = 8, dpi = 300, 
       units = "in", device = "png"
       )


plot_PA_jrad <- 
  jrad_df %>%
    dplyr::select(ID, PA_pre, PA_post) %>%
    tidyr::pivot_longer(cols = c(PA_pre, PA_post), names_to = "Time", values_to = "value") %>%
    dplyr::mutate(
      Time = stringr::str_replace(Time, "pre", "Pre"),
      Time = stringr::str_replace(Time, "post", "Post"), 
      Time = stringr::str_remove(Time, ".*_"),
      Time = stringr::str_remove(Time, "_"), 
      Time = factor(Time, levels = c("Pre", "Post"))) %>%
    group_by(ID) %>%
    ggstatsplot::ggwithinstats(
      x = Time,
      y = value,
      title = "Positive Emotions",
      xlab = "Time",
      ylab = "Positive Emotions",
      pairwise.comparisons = TRUE,
      pairwise.display = "significant",
      results.subtitle = TRUE,
      type = "parametric",
      bf.message = FALSE, 
      p.adjust.method = "none",
      point.path = TRUE,
      outlier.tagging = FALSE,
      ggtheme = ggprism::theme_prism(),
      # package = "RColorBrewer",  # "ggsci",
      # palette = "Dark",         # "default_jco",
      violin.args = list(width = 0.9, alpha = 0.2, size = 1, color = "black"),
      centrality.point.args = list(size = 5, color = "darkred"),
      centrality.label.args = list(size = 3, nudge_x = 0.2, segment.linetype = 5, fill = "#FFF8E7"), 
      ggplot.component = list(
        theme(
          plot.title = element_text(hjust = 0, size = 16),
          plot.subtitle = element_text(hjust = 0, size = 12), 
          plot.caption = element_text(hjust = 0, size = 12), 
          text = element_text(size = 14)
      ))
    ) + scale_colour_grey(start = 0.2, end = 0.2)   # hacky way to change point color

ggsave(plot_PA_jrad, 
       filename = "PA JRAD.png", 
       height = 8, width = 8, dpi = 300, 
       units = "in", device = "png"
       )


plot_NA_jrad <- 
  jrad_df %>%
    dplyr::select(ID, NA_pre, NA_post) %>%
    tidyr::pivot_longer(cols = c(NA_pre, NA_post), names_to = "Time", values_to = "value") %>%
    dplyr::mutate(
      Time = stringr::str_replace(Time, "pre", "Pre"),
      Time = stringr::str_replace(Time, "post", "Post"), 
      Time = stringr::str_remove(Time, ".*_"),
      Time = stringr::str_remove(Time, "_"), 
      Time = factor(Time, levels = c("Pre", "Post"))) %>%
    group_by(ID) %>%
    ggstatsplot::ggwithinstats(
      x = Time,
      y = value,
      title = "Negative Emotions",
      xlab = "Time",
      ylab = "Negative Emotions",
      pairwise.comparisons = TRUE,
      pairwise.display = "significant",
      results.subtitle = TRUE,
      type = "parametric",
      bf.message = FALSE, 
      p.adjust.method = "none",
      point.path = TRUE,
      outlier.tagging = FALSE,
      ggtheme = ggprism::theme_prism(),
      # package = "RColorBrewer",  # "ggsci",
      # palette = "Dark",         # "default_jco",
      violin.args = list(width = 0.9, alpha = 0.2, size = 1, color = "black"),
      centrality.point.args = list(size = 5, color = "darkred"),
      centrality.label.args = list(size = 3, nudge_x = 0.2, segment.linetype = 5, fill = "#FFF8E7"), 
      ggplot.component = list(
        theme(
          plot.title = element_text(hjust = 0, size = 16),
          plot.subtitle = element_text(hjust = 0, size = 12), 
          plot.caption = element_text(hjust = 0, size = 12), 
          text = element_text(size = 14)
      ))
    ) + scale_colour_grey(start = 0.2, end = 0.2)   # hacky way to change point color

ggsave(plot_NA_jrad, 
       filename = "NA JRAD.png", 
       height = 8, width = 8, dpi = 300, 
       units = "in", device = "png"
       )


plot_APS_jrad <- 
  jrad_df %>%
    dplyr::select(ID, APS_pre, APS_post) %>%
    tidyr::pivot_longer(cols = c(APS_pre, APS_post), names_to = "Time", values_to = "value") %>%
    dplyr::mutate(
      Time = stringr::str_replace(Time, "pre", "Pre"),
      Time = stringr::str_replace(Time, "post", "Post"), 
      Time = stringr::str_remove(Time, ".*_"),
      Time = stringr::str_remove(Time, "_"), 
      Time = factor(Time, levels = c("Pre", "Post"))) %>%
    group_by(ID) %>%
    ggstatsplot::ggwithinstats(
      x = Time,
      y = value,
      title = "Prosocial Attitudes",
      xlab = "Time",
      ylab = "Prosocial Attitudes",
      pairwise.comparisons = TRUE,
      pairwise.display = "significant",
      results.subtitle = TRUE,
      type = "parametric",
      bf.message = FALSE, 
      p.adjust.method = "none",
      point.path = TRUE,
      outlier.tagging = FALSE,
      ggtheme = ggprism::theme_prism(),
      # package = "RColorBrewer",  # "ggsci",
      # palette = "Dark",         # "default_jco",
      violin.args = list(width = 0.9, alpha = 0.2, size = 1, color = "black"),
      centrality.point.args = list(size = 5, color = "darkred"),
      centrality.label.args = list(size = 3, nudge_x = 0.2, segment.linetype = 5, fill = "#FFF8E7"), 
      ggplot.component = list(
        theme(
          plot.title = element_text(hjust = 0, size = 16),
          plot.subtitle = element_text(hjust = 0, size = 12), 
          plot.caption = element_text(hjust = 0, size = 12), 
          text = element_text(size = 14)
      ))
    ) + scale_colour_grey(start = 0.2, end = 0.2)   # hacky way to change point color

ggsave(plot_APS_jrad, 
       filename = "APS JRAD.png", 
       height = 8, width = 8, dpi = 300, 
       units = "in", device = "png"
       )
```

# ES - Prez

```{r}
plot_STAI_es <- 
  es_df %>%
    dplyr::select(ID, StaiS_pre, StaiS_post) %>%
    tidyr::pivot_longer(cols = c(StaiS_pre, StaiS_post), names_to = "Time", values_to = "value") %>%
    dplyr::mutate(
      Time = stringr::str_replace(Time, "pre", "Pre"),
      Time = stringr::str_replace(Time, "post", "Post"), 
      Time = stringr::str_remove(Time, ".*_"),
      Time = stringr::str_remove(Time, "_"), 
      Time = factor(Time, levels = c("Pre", "Post"))) %>%
    group_by(ID) %>%
    ggstatsplot::ggwithinstats(
      x = Time,
      y = value,
      title = "Anxiety",
      xlab = "Time",
      ylab = "Anxiety",
      pairwise.comparisons = TRUE,
      pairwise.display = "significant",
      results.subtitle = TRUE,
      type = "parametric",
      bf.message = FALSE, 
      p.adjust.method = "none",
      point.path = TRUE,
      outlier.tagging = FALSE,
      ggtheme = ggprism::theme_prism(),
      # package = "RColorBrewer",  # "ggsci",
      # palette = "Dark",         # "default_jco",
      violin.args = list(width = 0.9, alpha = 0.2, size = 1, color = "black"),
      centrality.point.args = list(size = 5, color = "darkred"),
      centrality.label.args = list(size = 3, nudge_x = 0.2, segment.linetype = 5, fill = "#FFF8E7"), 
      ggplot.component = list(
        theme(
          plot.title = element_text(hjust = 0, size = 16),
          plot.subtitle = element_text(hjust = 0, size = 12), 
          plot.caption = element_text(hjust = 0, size = 12), 
          text = element_text(size = 14)
      ))
    ) + scale_colour_grey(start = 0.2, end = 0.2)   # hacky way to change point color

ggsave(plot_STAI_es, 
       filename = "StaiS ES.png", 
       height = 8, width = 8, dpi = 300, 
       units = "in", device = "png"
       )


plot_PA_es <- 
  es_df %>%
    dplyr::select(ID, PA_pre, PA_post) %>%
    tidyr::pivot_longer(cols = c(PA_pre, PA_post), names_to = "Time", values_to = "value") %>%
    dplyr::mutate(
      Time = stringr::str_replace(Time, "pre", "Pre"),
      Time = stringr::str_replace(Time, "post", "Post"), 
      Time = stringr::str_remove(Time, ".*_"),
      Time = stringr::str_remove(Time, "_"), 
      Time = factor(Time, levels = c("Pre", "Post"))) %>%
    group_by(ID) %>%
    ggstatsplot::ggwithinstats(
      x = Time,
      y = value,
      title = "Positive Emotions",
      xlab = "Time",
      ylab = "Positive Emotions",
      pairwise.comparisons = TRUE,
      pairwise.display = "significant",
      results.subtitle = TRUE,
      type = "parametric",
      bf.message = FALSE, 
      p.adjust.method = "none",
      point.path = TRUE,
      outlier.tagging = FALSE,
      ggtheme = ggprism::theme_prism(),
      # package = "RColorBrewer",  # "ggsci",
      # palette = "Dark",         # "default_jco",
      violin.args = list(width = 0.9, alpha = 0.2, size = 1, color = "black"),
      centrality.point.args = list(size = 5, color = "darkred"),
      centrality.label.args = list(size = 3, nudge_x = 0.2, segment.linetype = 5, fill = "#FFF8E7"), 
      ggplot.component = list(
        theme(
          plot.title = element_text(hjust = 0, size = 16),
          plot.subtitle = element_text(hjust = 0, size = 12), 
          plot.caption = element_text(hjust = 0, size = 12), 
          text = element_text(size = 14)
      ))
    ) + scale_colour_grey(start = 0.2, end = 0.2)   # hacky way to change point color

ggsave(plot_PA_es, 
       filename = "PA ES.png", 
       height = 8, width = 8, dpi = 300, 
       units = "in", device = "png"
       )


plot_NA_es <- 
  es_df %>%
    dplyr::select(ID, NA_pre, NA_post) %>%
    tidyr::pivot_longer(cols = c(NA_pre, NA_post), names_to = "Time", values_to = "value") %>%
    dplyr::mutate(
      Time = stringr::str_replace(Time, "pre", "Pre"),
      Time = stringr::str_replace(Time, "post", "Post"), 
      Time = stringr::str_remove(Time, ".*_"),
      Time = stringr::str_remove(Time, "_"), 
      Time = factor(Time, levels = c("Pre", "Post"))) %>%
    group_by(ID) %>%
    ggstatsplot::ggwithinstats(
      x = Time,
      y = value,
      title = "Negative Emotions",
      xlab = "Time",
      ylab = "Negative Emotions",
      pairwise.comparisons = TRUE,
      pairwise.display = "significant",
      results.subtitle = TRUE,
      type = "parametric",
      bf.message = FALSE, 
      p.adjust.method = "none",
      point.path = TRUE,
      outlier.tagging = FALSE,
      ggtheme = ggprism::theme_prism(),
      # package = "RColorBrewer",  # "ggsci",
      # palette = "Dark",         # "default_jco",
      violin.args = list(width = 0.9, alpha = 0.2, size = 1, color = "black"),
      centrality.point.args = list(size = 5, color = "darkred"),
      centrality.label.args = list(size = 3, nudge_x = 0.2, segment.linetype = 5, fill = "#FFF8E7"), 
      ggplot.component = list(
        theme(
          plot.title = element_text(hjust = 0, size = 16),
          plot.subtitle = element_text(hjust = 0, size = 12), 
          plot.caption = element_text(hjust = 0, size = 12), 
          text = element_text(size = 14)
      ))
    ) + scale_colour_grey(start = 0.2, end = 0.2)   # hacky way to change point color

ggsave(plot_NA_es, 
       filename = "NA ES.png", 
       height = 8, width = 8, dpi = 300, 
       units = "in", device = "png"
       )


plot_APS_es <- 
  es_df %>%
    dplyr::select(ID, APS_pre, APS_post) %>%
    tidyr::pivot_longer(cols = c(APS_pre, APS_post), names_to = "Time", values_to = "value") %>%
    dplyr::mutate(
      Time = stringr::str_replace(Time, "pre", "Pre"),
      Time = stringr::str_replace(Time, "post", "Post"), 
      Time = stringr::str_remove(Time, ".*_"),
      Time = stringr::str_remove(Time, "_"), 
      Time = factor(Time, levels = c("Pre", "Post"))) %>%
    group_by(ID) %>%
    ggstatsplot::ggwithinstats(
      x = Time,
      y = value,
      title = "Prosocial Attitudes",
      xlab = "Time",
      ylab = "Prosocial Attitudes",
      pairwise.comparisons = TRUE,
      pairwise.display = "significant",
      results.subtitle = TRUE,
      type = "parametric",
      bf.message = FALSE, 
      p.adjust.method = "none",
      point.path = TRUE,
      outlier.tagging = FALSE,
      ggtheme = ggprism::theme_prism(),
      # package = "RColorBrewer",  # "ggsci",
      # palette = "Dark",         # "default_jco",
      violin.args = list(width = 0.9, alpha = 0.2, size = 1, color = "black"),
      centrality.point.args = list(size = 5, color = "darkred"),
      centrality.label.args = list(size = 3, nudge_x = 0.2, segment.linetype = 5, fill = "#FFF8E7"), 
      ggplot.component = list(
        theme(
          plot.title = element_text(hjust = 0, size = 16),
          plot.subtitle = element_text(hjust = 0, size = 12), 
          plot.caption = element_text(hjust = 0, size = 12), 
          text = element_text(size = 14)
      ))
    ) + scale_colour_grey(start = 0.2, end = 0.2)   # hacky way to change point color

ggsave(plot_APS_es, 
       filename = "APS ES.png", 
       height = 8, width = 8, dpi = 300, 
       units = "in", device = "png"
       )
```







# Only POST variables

```{r post_vars}
merged_df <- rbind(es_df, jrad_df)

# IOS
merged_df %>%
  group_by(Conditie) %>%
  rstatix::get_summary_stats(IOS)
merged_df %>%
  rstatix::t_test(IOS ~ Conditie) 
```





<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
