---
title: "<br> O1A Report" 
subtitle: "Final Report"
author: "<br> Claudiu Papasteri"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: 
    html_notebook:
            code_folding: hide
            toc: true
            toc_depth: 2
            number_sections: true
            theme: spacelab
            highlight: tango
            font-family: Arial
            fig_width: 10
            fig_height: 9
    pdf_document: 
            toc: true
            toc_depth: 2
            number_sections: true
            # fontsize: 11pt
            # geometry: margin=1in
            # fig_width: 7
            # fig_height: 6
            # fig_caption: true
    # github_document: 
            # toc: true
            # toc_depth: 2
            # html_preview: false
            # fig_width: 5
            # fig_height: 5
            # dev: jpeg
---


<!-- Setup -->


```{r setup, include = FALSE}
# kintr options
knitr::opts_chunk$set(
  comment = "#",
  collapse = TRUE,
  echo = TRUE, warning = TRUE, message = TRUE, cache = TRUE       # echo = False for github_document, but will be folded in html_notebook
)

# General R options and info
set.seed(111)               # in case we use randomized procedures       
options(scipen = 999)       # positive values bias towards fixed and negative towards scientific notation

# Load packages
if (!require("pacman")) install.packages("pacman")
packages <- c(
  "tidyverse",      # best thing that happend to me
  "psych",          # general purpose toolbox for personality, psychometric theory and experimental psychology
  "papaja",         # for APA style
  "broom",          # for tidy modelling
  "ggplot2",        # best plots
  "ggpubr",         # ggplot2 to publication quality
  "DT",             # nice searchable and downloadable tables
  "summarytools",
  "plotly",
  "gridExtra",
  "grid"
  # , ...
)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(char = packages)

# Themes for ggplot2 ploting (here used APA style)
theme_set(theme_apa())
```

```{r working_directory, include = FALSE}
# if needed
# wd = "./o1a-report"
# setwd(wd)
```


<!-- Report -->


# Load data

```{r raw_data, results = 'hide', cache.extra = file.info("diamonds.csv")}
# Read
file = "DATE O1A Complete.xlsx"

Date <- readxl::read_xlsx(file, sheet = "Date zilnice", skip = 5, col_names = FALSE)

Date_sop <- readRDS("O1a_Processed_SOP.RDS")
```


## Processing data

```{r processed_data, cache = TRUE, dependson = "raw_data"}
# Clean
varnames <- c("Nr_crt", "ID", "Nume_Prenume", "Zi", "Vas_stres_pre", "Vas_bine_pre",
             sprintf("Stais_pre_%01d", seq(1,20)),
             "SOP",
             "IOS_mama", "IOS_tata", "IOS_iubit", "IOS_prieten", "IOS_personalitate",
             "Vas_rel_global", "Vas_rel_arousal",
             "CRQ_1", "CRQ_2", "CRQ_3", "CRQ_4", "CRQ_5", "CRQ_6",
             "Vas_stres_post", "Vas_bine_post",
             sprintf("Stais_post_%01d", seq(1,20))
)
names(Date) <- varnames   # nume noi
Date <- Date[-c(1:2),]    # scoatem randurile cu numele precedente
Date$Nr_crt <- 1:nrow(Date)   # era gol, asa ca numerotam randurile ca sa avem acesta variabila 

# Process NAs
Date <- Date %>% 
    na_if("na") %>%  
    mutate(NA_per_row = rowSums(is.na(.)))     # count NAs by row

Date <- Date %>% 
    filter(NA_per_row < 20)         # arbitrary cutoff for NAs on columns ... it is normal to have 4 NAs for all columns

# Convert to numeric
varsnumeric <- c("Zi", "Vas_stres_pre", "Vas_bine_pre",
                 sprintf("Stais_pre_%01d", seq(1,20)),
                 "IOS_mama", "IOS_tata", "IOS_iubit", "IOS_prieten", "IOS_personalitate",
                 "Vas_rel_global", "Vas_rel_arousal",
                 "CRQ_1", "CRQ_2", "CRQ_3", "CRQ_4", "CRQ_5", "CRQ_6",
                 "Vas_stres_post", "Vas_bine_post",
                  sprintf("Stais_post_%01d", seq(1,20)))

Date <- Date %>% 
  mutate_at(varsnumeric, as.numeric)

# which(Date$Stais_post_11 == 47)    # typo Stais_post_11 value of 47 -> corrected to 4
Date$Stais_post_11[Date$Stais_post_11 == 47] <- 4
```

<!-- Inspect Data - switched off -->
```{r inspectdata, echo=FALSE, results="hide"} 
# print(summarytools::dfSummary(Date, style = 'grid', plain.ascii = FALSE, graph.magnif = 0.85),    # suppress output
#       method = 'render', headings = FALSE)
# str(Date, list.len=ncol(Date))  # data types are fine
```


## Compute new variables

```{r derived_data, cache = TRUE, dependson = "processed_data"}
# Compute new variables 
Conditie <- Date %>% 
    select(Nr_crt, ID, IOS_mama, IOS_tata, IOS_iubit, IOS_prieten, IOS_personalitate) %>% 
    gather(type, value, -c(Nr_crt, ID)) %>% 
    mutate(Conditie = ifelse(!is.na(value), type, NA) ) %>%
    mutate(Conditie = str_replace(Conditie, "IOS_", "")) %>%
    arrange(Nr_crt) %>%
    select(Conditie) %>% na.omit() 
Date$Conditie <- Conditie$Conditie     # tidyverse returns tibble, must do this
IOS <- Date %>% 
  mutate(IOS = coalesce(IOS_mama, IOS_tata, IOS_iubit, IOS_prieten, IOS_personalitate)) %>%
  select(IOS)
Date$IOS <- IOS$IOS   # tidyverse returns tibble, must do this
rm(Conditie, IOS)    # remove 2 tibbles

# Scoring Stai   (convert numeric - VAS)
itemiVAS <- c(5, 6, 41, 42)

itemiStaiS_pre <- 7:26
itemiStaiS_post <- 43:62
ReversedItems <- c(1,2,5,8,10,11,15,16,19,20)

Date <- Date %>%                 
  replace(Date == "na", NA) %>%        # scimbam codarea cu na a Doinei
  mutate_at(vars(itemiStaiS_pre), funs(as.numeric)) %>%        # facem coloanele numerice pt STAI
  mutate_at(vars(itemiStaiS_post), funs(as.numeric)) %>% 
  mutate_at(vars(itemiVAS), funs(as.numeric))

Date[ ,itemiStaiS_pre[ReversedItems]] = 5 - Date[ ,itemiStaiS_pre[ReversedItems]]
Date[ ,itemiStaiS_post[ReversedItems]] = 5 - Date[ ,itemiStaiS_post[ReversedItems]]

Date$StaiS_pre = rowSums(Date[ ,itemiStaiS_pre], na.rm=T ) * NA ^ (rowSums(!is.na(Date[ ,itemiStaiS_pre])) == 0)
Date$StaiS_post = rowSums(Date[ ,itemiStaiS_post], na.rm=T ) * NA ^ (rowSums(!is.na(Date[ ,itemiStaiS_post])) == 0)
```


## Merge with SOP
```{r merged_data, cache = TRUE, dependson = "derived_data", warning = FALSE}
# warning + FALSE for joining character vector and factor, coercing into character vector automatically
Date_formerge <-
  Date %>%
  mutate(ID = word(ID, 1))

Date_sop_formerge <-
  Date_sop %>%
  select(FileNames, ID, Conditie, PrePost, 
         Ones:rThrees45) %>%
  gather(variable, value, Ones:rThrees45) %>%
  unite(VarCond, variable, PrePost) %>%
  spread(VarCond, value) %>%
  group_by(ID, Conditie) %>%
  summarise_all(funs(first(.[!is.na(.)])))             # this collapses the rows with NA
  
Date_merged <- left_join(Date_formerge, Date_sop_formerge, by = c("ID", "Conditie"))

```

## Table of derived variables and SOP

```{r table_derived_data}
varnottable <- c("Nume_Prenume", "NA_per_row",
                 "IOS_mama", "IOS_tata", "IOS_iubit", "IOS_prieten", "IOS_personalitate",
                 sprintf("Stais_pre_%01d", seq(1,20)), 
                 sprintf("Stais_post_%01d", seq(1,20)))

Date_merged %>%                              
  select(-varnottable) %>%
    DT::datatable(                                  # excel downloadable  DT table
      extensions = 'Buttons',
      options = list(pageLength = 20,
                     scrollX='500px', 
                     dom = 'Bfrtip', 
                     buttons = c('excel', "csv")))
```


<br>
<br>

# SOP

```{r sop_functions}
# ## Independent Comparisons (eg for Ones) 
# # Plot indendent 
# ggplot(Date_sop, aes(x = PrePost, y = Ones)) +
#   geom_boxplot() +
#   facet_wrap(~Conditie) +
#   ggpubr::stat_compare_means(method = "t.test", paired = FALSE, comparisons = list(c("Pre","Post")))
# 
# # t test independent
# Date_sop %>% 
#   group_by(Conditie) %>% 
#   do(broom::tidy(t.test(.$Ones ~ .$PrePost, 
#                         mu = 0, 
#                         alt = "two.sided", 
#                         paired = FALSE, 
#                         conf.level = 0.95)))

## Paired Comparisons 
# Filter data for Paired Comparisons 
Date_Paired <- 
  Date_sop %>%
  mutate(PrePost = forcats::fct_relevel(PrePost, 'Pre', 'Post')) %>%               # change level order for plot
  group_by(ID, Conditie) %>%
  filter(n() != 1) %>%                                                             # exclude cases that dont have both Pre and Post data
  ungroup()

## Function for paired comparison plot
sop_paired_plot <- function(data, var, cond){
  var <- rlang::enquo(var)
  cond <- rlang::enquo(cond)
  ggplot(data, aes(x = !!cond, y = !!var)) +
    geom_boxplot() +
    stat_summary(fun.data = mean_se,  colour = "darkred") +
    xlab("") +
    facet_wrap(~Conditie) +
    ggpubr::stat_compare_means(method = "t.test", 
                               paired = TRUE, 
                               comparisons = list(c("Pre", "Post")))              # didn't include comparison list in func args
}

# Function t test paired
sop_paired_t <- function(data, var, cond){
  var <- deparse(substitute(var))
  cond <- deparse(substitute(cond))
  formula <- reformulate(cond, response = var)
  data %>%
    group_by(Conditie) %>%
    do(broom::tidy(t.test(data = ., formula,                                      # careful, this is a formula: var ~ PrePost
                          mu = 0,
                          alt = "two.sided",
                          paired = TRUE,
                          conf.level = 0.95)))
}
```

## Plots with p values and t test
```{r sop_plots_tests, fig.width = 10, fig.asp = 0.8}
# Plots and t tests
sop_paired_plot(data = Date_Paired, var = Ones, cond = PrePost)                   # plot Ones 
sop_paired_t(data = Date_Paired, var = Ones, cond = PrePost) %>%                  # t test Ones
  knitr::kable(caption = "Ones", digits = 2, format = 'pandoc')                   # need pandoc to print kable caption
sop_paired_plot(data = Date_Paired, var = Twos, cond = PrePost)
sop_paired_t(data = Date_Paired, var = Twos, cond = PrePost) %>%
  knitr::kable(caption = "Twos", digits = 2, format = 'pandoc')                   
sop_paired_plot(data = Date_Paired, var = Threes, cond = PrePost)
sop_paired_t(data = Date_Paired, var = Threes, cond = PrePost) %>%
  knitr::kable(caption = "Threes", digits = 2, format = 'pandoc')

sop_paired_plot(data = Date_Paired, var = Ones45, cond = PrePost)                 # plot Ones before 45s
sop_paired_t(data = Date_Paired, var = Ones45, cond = PrePost) %>%                # t test Ones before 45s
  knitr::kable(caption = "Ones45", digits = 2, format = 'pandoc')
sop_paired_plot(data = Date_Paired, var = Twos45, cond = PrePost)
sop_paired_t(data = Date_Paired, var = Twos45, cond = PrePost) %>%
  knitr::kable(caption = "Twos45", digits = 2, format = 'pandoc')
sop_paired_plot(data = Date_Paired, var = Threes45, cond = PrePost)
sop_paired_t(data = Date_Paired, var = Threes45, cond = PrePost) %>%
  knitr::kable(caption = "Threes45", digits = 2, format = 'pandoc')

sop_paired_plot(data = Date_Paired, var = rOnes, cond = PrePost)                  # plot ratio Ones to total presses
sop_paired_t(data = Date_Paired, var = rOnes, cond = PrePost) %>%                 # t test ratio Ones to total presses
  knitr::kable(caption = "rOnes", digits = 2, format = 'pandoc')
sop_paired_plot(data = Date_Paired, var = rTwos, cond = PrePost)
sop_paired_t(data = Date_Paired, var = rTwos, cond = PrePost) %>%
  knitr::kable(caption = "rTwos", digits = 2, format = 'pandoc')
sop_paired_plot(data = Date_Paired, var = rThrees, cond = PrePost)
sop_paired_t(data = Date_Paired, var = rThrees, cond = PrePost) %>%
  knitr::kable(caption = "rThrees", digits = 2, format = 'pandoc')
```


<br>
<br>

<!-- Session Info and License -->

<br>

# Session Info
```{r session_info, echo = FALSE, results = 'markup'}
sessionInfo()    
```

<!-- Footer -->
&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://github.com/ClaudiuPapasteri/">Claudiu Papasteri</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>claudiu.papasteri@gmail.com</em></span></p>
&nbsp;
